// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request Option for processing Cloud AI Document in CW Document.
public struct CloudAIDocumentOption: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether to convert all the entities to properties.
  public var enableEntitiesConversions: Swift.Bool = Swift.Bool()

  /// If set, only selected entities will be converted to properties.
  public var customizedEntitiesPropertiesConversions: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudAIDocumentOption`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudAIDocumentOption().with { $0.enableEntitiesConversions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableEntitiesConversions = CodingKeys(stringValue: "enableEntitiesConversions")
    static let customizedEntitiesPropertiesConversions = CodingKeys(
      stringValue: "customizedEntitiesPropertiesConversions")

    static let _knownKeys: Set<Swift.String> = [
      "enableEntitiesConversions",
      "customizedEntitiesPropertiesConversions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableEntitiesConversions)
    {
      self.enableEntitiesConversions = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .customizedEntitiesPropertiesConversions)
    {
      self.customizedEntitiesPropertiesConversions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enableEntitiesConversions, forKey: .enableEntitiesConversions)
    try container.encode(
      self.customizedEntitiesPropertiesConversions, forKey: .customizedEntitiesPropertiesConversions
    )
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.CloudAIDocumentOption"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
