// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleLongRunning

/// Response message for DocumentService.CreateDocument.
public struct CreateDocumentResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Document created after executing create request.
  public var document: Document? = nil

  /// Output from Rule Engine recording the rule evaluator and action executor's
  /// output.
  ///
  /// Refer format in: google/cloud/contentwarehouse/v1/rule_engine.proto
  public var ruleEngineOutput: RuleEngineOutput? = nil

  /// Additional information for the API invocation, such as the request tracking
  /// id.
  public var metadata: ResponseMetadata? = nil

  /// post-processing LROs
  public var longRunningOperations: [GoogleLongRunning.Operation] = []

  /// Initialize a new instance of `CreateDocumentResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDocumentResponse().with { $0.document = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.CreateDocumentResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
