// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// This service lets you manage document schema.
///
/// @Snippet(path: "DocumentSchemaServiceQuickstart")
public final class DocumentSchemaServiceClient: Clients.DocumentSchemaServiceProtocol, Sendable {
  let inner: any Clients.DocumentSchemaServiceStub

  /// Creates a new `DocumentSchemaServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DocumentSchemaServiceStub = try Clients.DocumentSchemaServiceTransport(
      options)
    inner = Clients.DocumentSchemaServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DocumentSchemaServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a document schema.
  ///
  /// @Snippet(path: "DocumentSchemaService_CreateDocumentSchema")
  public func createDocumentSchema(
    request: CreateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    try await self.inner.createDocumentSchema(request: request, options: options)
  }

  /// Updates a Document Schema. Returns INVALID_ARGUMENT if the name of the
  /// Document Schema is non-empty and does not equal the existing name.
  /// Supports only appending new properties, adding new ENUM possible values,
  /// and updating the
  /// [EnumTypeOptions.validation_check_disabled][google.cloud.contentwarehouse.v1.EnumTypeOptions.validation_check_disabled]
  /// flag for ENUM possible values. Updating existing properties will result
  /// into INVALID_ARGUMENT.
  ///
  /// [google.cloud.contentwarehouse.v1.EnumTypeOptions.validation_check_disabled]: <doc:EnumTypeOptions/validationCheckDisabled>
  ///
  /// @Snippet(path: "DocumentSchemaService_UpdateDocumentSchema")
  public func updateDocumentSchema(
    request: UpdateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    try await self.inner.updateDocumentSchema(request: request, options: options)
  }

  /// Gets a document schema. Returns NOT_FOUND if the document schema does not
  /// exist.
  ///
  /// @Snippet(path: "DocumentSchemaService_GetDocumentSchema")
  public func getDocumentSchema(
    request: GetDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    try await self.inner.getDocumentSchema(request: request, options: options)
  }

  /// Deletes a document schema. Returns NOT_FOUND if the document schema does
  /// not exist. Returns BAD_REQUEST if the document schema has documents
  /// depending on it.
  ///
  /// @Snippet(path: "DocumentSchemaService_DeleteDocumentSchema")
  public func deleteDocumentSchema(
    request: DeleteDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDocumentSchema(request: request, options: options)
  }

  /// Lists document schemas.
  ///
  /// @Snippet(path: "DocumentSchemaService_ListDocumentSchemas")
  public func listDocumentSchemas(
    request: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse {
    try await self.inner.listDocumentSchemas(request: request, options: options)
  }

  /// Lists document schemas.
  ///
  /// @Snippet(path: "DocumentSchemaService_ListDocumentSchemas")
  public func listDocumentSchemas(
    byItem: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DocumentSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDocumentSchemas(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentSchemaService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DocumentSchemaServiceClient`.
  ///
  /// To mock `DocumentSchemaServiceClient` change your functions to receive
  /// `some DocumentSchemaServiceProtocol` or `any DocumentSchemaServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DocumentSchemaServiceProtocol {
    /// See `DocumentSchemaServiceClient.createDocumentSchema`.
    func createDocumentSchema(request: CreateDocumentSchemaRequest) async throws
      -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.createDocumentSchema`.
    func createDocumentSchema(
      parent: Swift.String,
      documentSchema: DocumentSchema?,
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.updateDocumentSchema`.
    func updateDocumentSchema(request: UpdateDocumentSchemaRequest) async throws
      -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.updateDocumentSchema`.
    func updateDocumentSchema(
      name: Swift.String,
      documentSchema: DocumentSchema?,
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.getDocumentSchema`.
    func getDocumentSchema(request: GetDocumentSchemaRequest) async throws
      -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.getDocumentSchema`.
    func getDocumentSchema(
      name: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.deleteDocumentSchema`.
    func deleteDocumentSchema(request: DeleteDocumentSchemaRequest) async throws

    /// See `DocumentSchemaServiceClient.deleteDocumentSchema`.
    func deleteDocumentSchema(
      name: Swift.String,
    ) async throws

    /// See `DocumentSchemaServiceClient.listDocumentSchemas`.
    func listDocumentSchemas(request: ListDocumentSchemasRequest) async throws
      -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse

    /// See `DocumentSchemaServiceClient.listDocumentSchemas`.
    func listDocumentSchemas(
      byItem: ListDocumentSchemasRequest
    ) throws -> any AsyncSequence<DocumentSchema, Swift.Error>

    /// See `DocumentSchemaServiceClient.listDocumentSchemas`.
    func listDocumentSchemas(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DocumentSchema, Swift.Error>

    /// See `DocumentSchemaServiceClient.createDocumentSchema`.
    func createDocumentSchema(
      request: CreateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.updateDocumentSchema`.
    func updateDocumentSchema(
      request: UpdateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.getDocumentSchema`.
    func getDocumentSchema(
      request: GetDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema

    /// See `DocumentSchemaServiceClient.deleteDocumentSchema`.
    func deleteDocumentSchema(
      request: DeleteDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DocumentSchemaServiceClient.listDocumentSchemas`.
    func listDocumentSchemas(
      request: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse

    /// See `DocumentSchemaServiceClient.listDocumentSchemas`.
    func listDocumentSchemas(
      byItem: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DocumentSchema, Swift.Error>
  }
}

// Default implementations
extension Clients.DocumentSchemaServiceProtocol {
  public func createDocumentSchema(request: CreateDocumentSchemaRequest) async throws
    -> GoogleCloudContentWarehouseV1.DocumentSchema
  {
    try await self.createDocumentSchema(request: request, options: .init())
  }

  public func createDocumentSchema(
    request: CreateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDocumentSchema(
    parent: Swift.String,
    documentSchema: DocumentSchema?,
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    let request = CreateDocumentSchemaRequest().with {
      $0.parent = parent
      $0.documentSchema = documentSchema
    }
    return try await self.createDocumentSchema(request: request)
  }

  public func updateDocumentSchema(request: UpdateDocumentSchemaRequest) async throws
    -> GoogleCloudContentWarehouseV1.DocumentSchema
  {
    try await self.updateDocumentSchema(request: request, options: .init())
  }

  public func updateDocumentSchema(
    request: UpdateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDocumentSchema(
    name: Swift.String,
    documentSchema: DocumentSchema?,
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    let request = UpdateDocumentSchemaRequest().with {
      $0.name = name
      $0.documentSchema = documentSchema
    }
    return try await self.updateDocumentSchema(request: request)
  }

  public func getDocumentSchema(request: GetDocumentSchemaRequest) async throws
    -> GoogleCloudContentWarehouseV1.DocumentSchema
  {
    try await self.getDocumentSchema(request: request, options: .init())
  }

  public func getDocumentSchema(
    request: GetDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDocumentSchema(
    name: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
    let request = GetDocumentSchemaRequest().with {
      $0.name = name
    }
    return try await self.getDocumentSchema(request: request)
  }

  public func deleteDocumentSchema(request: DeleteDocumentSchemaRequest) async throws {
    try await self.deleteDocumentSchema(request: request, options: .init())
  }

  public func deleteDocumentSchema(
    request: DeleteDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDocumentSchema(
    name: Swift.String,
  ) async throws {
    let request = DeleteDocumentSchemaRequest().with {
      $0.name = name
    }
    try await self.deleteDocumentSchema(request: request)
  }

  public func listDocumentSchemas(request: ListDocumentSchemasRequest) async throws
    -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse
  {
    try await self.listDocumentSchemas(request: request, options: .init())
  }

  public func listDocumentSchemas(
    request: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDocumentSchemas(
    byItem: ListDocumentSchemasRequest
  ) throws -> any AsyncSequence<DocumentSchema, Swift.Error> {
    try self.listDocumentSchemas(byItem: byItem, options: .init())
  }

  public func listDocumentSchemas(
    byItem: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DocumentSchema, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDocumentSchemas(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DocumentSchema, Swift.Error> {
    let request = ListDocumentSchemasRequest().with {
      $0.parent = parent
    }
    return try self.listDocumentSchemas(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
