// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// References to the documents.
public struct DocumentReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the referenced document.
  public var documentName: Swift.String = Swift.String()

  /// display_name of the referenced document; this name does not need to be
  /// consistent to the display_name in the Document proto, depending on the ACL
  /// constraint.
  public var displayName: Swift.String = Swift.String()

  /// Stores the subset of the referenced document's content.
  /// This is useful to allow user peek the information of the referenced
  /// document.
  public var snippet: Swift.String = Swift.String()

  /// The document type of the document being referenced.
  public var documentIsFolder: Swift.Bool = Swift.Bool()

  /// Output only. The time when the document is last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the document is created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the document is deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Document is a folder with retention policy.
  public var documentIsRetentionFolder: Swift.Bool = Swift.Bool()

  /// Document is a folder with legal hold.
  public var documentIsLegalHoldFolder: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DocumentReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentReference().with { $0.documentName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.DocumentReference"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
