// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleCloudGax

/// This service lets you manage document.
///
/// @Snippet(path: "DocumentServiceQuickstart")
public final class DocumentServiceClient: Clients.DocumentServiceProtocol, Sendable {
  let inner: any Clients.DocumentServiceStub

  /// Creates a new `DocumentServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DocumentServiceStub = try Clients.DocumentServiceTransport(options)
    inner = Clients.DocumentServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DocumentServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a document.
  ///
  /// @Snippet(path: "DocumentService_CreateDocument")
  public func createDocument(
    request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.CreateDocumentResponse {
    try await self.inner.createDocument(request: request, options: options)
  }

  /// Gets a document. Returns NOT_FOUND if the document does not exist.
  ///
  /// @Snippet(path: "DocumentService_GetDocument")
  public func getDocument(
    request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    try await self.inner.getDocument(request: request, options: options)
  }

  /// Updates a document. Returns INVALID_ARGUMENT if the name of the document
  /// is non-empty and does not equal the existing name.
  ///
  /// @Snippet(path: "DocumentService_UpdateDocument")
  public func updateDocument(
    request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse {
    try await self.inner.updateDocument(request: request, options: options)
  }

  /// Deletes a document. Returns NOT_FOUND if the document does not exist.
  ///
  /// @Snippet(path: "DocumentService_DeleteDocument")
  public func deleteDocument(
    request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDocument(request: request, options: options)
  }

  /// Searches for documents using provided
  /// [SearchDocumentsRequest][google.cloud.contentwarehouse.v1.SearchDocumentsRequest].
  /// This call only returns documents that the caller has permission to search
  /// against.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest]: <doc:SearchDocumentsRequest>
  ///
  /// @Snippet(path: "DocumentService_SearchDocuments")
  public func searchDocuments(
    request: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse {
    try await self.inner.searchDocuments(request: request, options: options)
  }

  /// Searches for documents using provided
  /// [SearchDocumentsRequest][google.cloud.contentwarehouse.v1.SearchDocumentsRequest].
  /// This call only returns documents that the caller has permission to search
  /// against.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest]: <doc:SearchDocumentsRequest>
  ///
  /// @Snippet(path: "DocumentService_SearchDocuments")
  public func searchDocuments(
    byItem: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchDocuments(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lock the document so the document cannot be updated by other users.
  ///
  /// @Snippet(path: "DocumentService_LockDocument")
  public func lockDocument(
    request: LockDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    try await self.inner.lockDocument(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns NOT_FOUND error if
  /// the resource does not exist. Returns an empty policy if the resource exists
  /// but does not have a policy set.
  ///
  /// @Snippet(path: "DocumentService_FetchAcl")
  public func fetchAcl(
    request: FetchAclRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.FetchAclResponse {
    try await self.inner.fetchAcl(request: request, options: options)
  }

  /// Sets the access control policy for a resource. Replaces any existing
  /// policy.
  ///
  /// @Snippet(path: "DocumentService_SetAcl")
  public func setAcl(
    request: SetAclRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse {
    try await self.inner.setAcl(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DocumentServiceClient`.
  ///
  /// To mock `DocumentServiceClient` change your functions to receive
  /// `some DocumentServiceProtocol` or `any DocumentServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DocumentServiceProtocol {
    /// See `DocumentServiceClient.createDocument`.
    func createDocument(request: CreateDocumentRequest) async throws
      -> GoogleCloudContentWarehouseV1.CreateDocumentResponse

    /// See `DocumentServiceClient.createDocument`.
    func createDocument(
      parent: Swift.String,
      document: Document?,
    ) async throws -> GoogleCloudContentWarehouseV1.CreateDocumentResponse

    /// See `DocumentServiceClient.getDocument`.
    func getDocument(request: GetDocumentRequest) async throws
      -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.getDocument`.
    func getDocument(
      name: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.updateDocument`.
    func updateDocument(request: UpdateDocumentRequest) async throws
      -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse

    /// See `DocumentServiceClient.updateDocument`.
    func updateDocument(
      name: Swift.String,
      document: Document?,
    ) async throws -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse

    /// See `DocumentServiceClient.deleteDocument`.
    func deleteDocument(request: DeleteDocumentRequest) async throws

    /// See `DocumentServiceClient.deleteDocument`.
    func deleteDocument(
      name: Swift.String,
    ) async throws

    /// See `DocumentServiceClient.searchDocuments`.
    func searchDocuments(request: SearchDocumentsRequest) async throws
      -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse

    /// See `DocumentServiceClient.searchDocuments`.
    func searchDocuments(
      byItem: SearchDocumentsRequest
    ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error>

    /// See `DocumentServiceClient.searchDocuments`.
    func searchDocuments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error>

    /// See `DocumentServiceClient.lockDocument`.
    func lockDocument(request: LockDocumentRequest) async throws
      -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.lockDocument`.
    func lockDocument(
      name: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.fetchAcl`.
    func fetchAcl(request: FetchAclRequest) async throws
      -> GoogleCloudContentWarehouseV1.FetchAclResponse

    /// See `DocumentServiceClient.fetchAcl`.
    func fetchAcl(
      resource: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.FetchAclResponse

    /// See `DocumentServiceClient.setAcl`.
    func setAcl(request: SetAclRequest) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse

    /// See `DocumentServiceClient.setAcl`.
    func setAcl(
      resource: Swift.String,
      policy: GoogleIAMV1.Policy?,
    ) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse

    /// See `DocumentServiceClient.createDocument`.
    func createDocument(
      request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.CreateDocumentResponse

    /// See `DocumentServiceClient.getDocument`.
    func getDocument(
      request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.updateDocument`.
    func updateDocument(
      request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse

    /// See `DocumentServiceClient.deleteDocument`.
    func deleteDocument(
      request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DocumentServiceClient.searchDocuments`.
    func searchDocuments(
      request: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse

    /// See `DocumentServiceClient.searchDocuments`.
    func searchDocuments(
      byItem: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error>

    /// See `DocumentServiceClient.lockDocument`.
    func lockDocument(
      request: LockDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.Document

    /// See `DocumentServiceClient.fetchAcl`.
    func fetchAcl(
      request: FetchAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.FetchAclResponse

    /// See `DocumentServiceClient.setAcl`.
    func setAcl(
      request: SetAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse
  }
}

// Default implementations
extension Clients.DocumentServiceProtocol {
  public func createDocument(request: CreateDocumentRequest) async throws
    -> GoogleCloudContentWarehouseV1.CreateDocumentResponse
  {
    try await self.createDocument(request: request, options: .init())
  }

  public func createDocument(
    request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.CreateDocumentResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDocument(
    parent: Swift.String,
    document: Document?,
  ) async throws -> GoogleCloudContentWarehouseV1.CreateDocumentResponse {
    let request = CreateDocumentRequest().with {
      $0.parent = parent
      $0.document = document
    }
    return try await self.createDocument(request: request)
  }

  public func getDocument(request: GetDocumentRequest) async throws
    -> GoogleCloudContentWarehouseV1.Document
  {
    try await self.getDocument(request: request, options: .init())
  }

  public func getDocument(
    request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDocument(
    name: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    let request = GetDocumentRequest().with {
      $0.name = name
    }
    return try await self.getDocument(request: request)
  }

  public func updateDocument(request: UpdateDocumentRequest) async throws
    -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse
  {
    try await self.updateDocument(request: request, options: .init())
  }

  public func updateDocument(
    request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDocument(
    name: Swift.String,
    document: Document?,
  ) async throws -> GoogleCloudContentWarehouseV1.UpdateDocumentResponse {
    let request = UpdateDocumentRequest().with {
      $0.name = name
      $0.document = document
    }
    return try await self.updateDocument(request: request)
  }

  public func deleteDocument(request: DeleteDocumentRequest) async throws {
    try await self.deleteDocument(request: request, options: .init())
  }

  public func deleteDocument(
    request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDocument(
    name: Swift.String,
  ) async throws {
    let request = DeleteDocumentRequest().with {
      $0.name = name
    }
    try await self.deleteDocument(request: request)
  }

  public func searchDocuments(request: SearchDocumentsRequest) async throws
    -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse
  {
    try await self.searchDocuments(request: request, options: .init())
  }

  public func searchDocuments(
    request: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchDocuments(
    byItem: SearchDocumentsRequest
  ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error> {
    try self.searchDocuments(byItem: byItem, options: .init())
  }

  public func searchDocuments(
    byItem: SearchDocumentsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.SearchDocumentsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchDocuments(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SearchDocumentsResponse.MatchingDocument, Swift.Error> {
    let request = SearchDocumentsRequest().with {
      $0.parent = parent
    }
    return try self.searchDocuments(byItem: request)
  }

  public func lockDocument(request: LockDocumentRequest) async throws
    -> GoogleCloudContentWarehouseV1.Document
  {
    try await self.lockDocument(request: request, options: .init())
  }

  public func lockDocument(
    request: LockDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func lockDocument(
    name: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.Document {
    let request = LockDocumentRequest().with {
      $0.name = name
    }
    return try await self.lockDocument(request: request)
  }

  public func fetchAcl(request: FetchAclRequest) async throws
    -> GoogleCloudContentWarehouseV1.FetchAclResponse
  {
    try await self.fetchAcl(request: request, options: .init())
  }

  public func fetchAcl(
    request: FetchAclRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.FetchAclResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func fetchAcl(
    resource: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.FetchAclResponse {
    let request = FetchAclRequest().with {
      $0.resource = resource
    }
    return try await self.fetchAcl(request: request)
  }

  public func setAcl(request: SetAclRequest) async throws
    -> GoogleCloudContentWarehouseV1.SetAclResponse
  {
    try await self.setAcl(request: request, options: .init())
  }

  public func setAcl(
    request: SetAclRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setAcl(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleCloudContentWarehouseV1.SetAclResponse {
    let request = SetAclRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setAcl(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
