// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class DocumentSchemaServiceLogging: DocumentSchemaServiceStub {
    let inner: any DocumentSchemaServiceStub
    let logger: Logger

    public init(_ inner: any DocumentSchemaServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-contentwarehouse-v1"
      logger[metadataKey: "gcp.client.service"] = "contentwarehouse"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DocumentSchemaService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createDocumentSchema(
      request: CreateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDocumentSchema",
        action: {
          (r: CreateDocumentSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.DocumentSchema
          in
          return try await self.inner.createDocumentSchema(request: r, options: o)
        })
    }

    public func updateDocumentSchema(
      request: UpdateDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDocumentSchema",
        action: {
          (r: UpdateDocumentSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.DocumentSchema
          in
          return try await self.inner.updateDocumentSchema(request: r, options: o)
        })
    }

    public func getDocumentSchema(
      request: GetDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentSchema {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDocumentSchema",
        action: {
          (r: GetDocumentSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.DocumentSchema
          in
          return try await self.inner.getDocumentSchema(request: r, options: o)
        })
    }

    public func deleteDocumentSchema(
      request: DeleteDocumentSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDocumentSchema",
        action: {
          (r: DeleteDocumentSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDocumentSchema(request: r, options: o)
        })
    }

    public func listDocumentSchemas(
      request: ListDocumentSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDocumentSchemas",
        action: {
          (r: ListDocumentSchemasRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.ListDocumentSchemasResponse
          in
          return try await self.inner.listDocumentSchemas(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
