// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A document schema used to define document structure.
public struct DocumentSchema: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the document schema.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  ///
  /// The name is ignored when creating a document schema.
  public var name: Swift.String = Swift.String()

  /// Required. Name of the schema given by the user. Must be unique per project.
  public var displayName: Swift.String = Swift.String()

  /// Document details.
  public var propertyDefinitions: [PropertyDefinition] = []

  /// Document Type, true refers the document is a folder, otherwise it is
  /// a typical document.
  public var documentIsFolder: Swift.Bool = Swift.Bool()

  /// Output only. The time when the document schema is last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the document schema is created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Schema description.
  public var description: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DocumentSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentSchema().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let propertyDefinitions = CodingKeys(stringValue: "propertyDefinitions")
    static let documentIsFolder = CodingKeys(stringValue: "documentIsFolder")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "propertyDefinitions",
      "documentIsFolder",
      "updateTime",
      "createTime",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      [PropertyDefinition].self, forKey: .propertyDefinitions)
    {
      self.propertyDefinitions = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .documentIsFolder) {
      self.documentIsFolder = value
    }
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.propertyDefinitions, forKey: .propertyDefinitions)
    try container.encode(self.documentIsFolder, forKey: .documentIsFolder)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.description, forKey: .description)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.DocumentSchema"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
