// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// This service lets you manage document-links.
/// Document-Links are treated as sub-resources under source documents.
///
/// @Snippet(path: "DocumentLinkServiceQuickstart")
public final class DocumentLinkServiceClient: Clients.DocumentLinkServiceProtocol, Sendable {
  let inner: any Clients.DocumentLinkServiceStub

  /// Creates a new `DocumentLinkServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DocumentLinkServiceStub = try Clients.DocumentLinkServiceTransport(
      options)
    inner = Clients.DocumentLinkServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DocumentLinkServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Return all target document-links from the document.
  ///
  /// @Snippet(path: "DocumentLinkService_ListLinkedTargets")
  public func listLinkedTargets(
    request: ListLinkedTargetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse {
    try await self.inner.listLinkedTargets(request: request, options: options)
  }

  /// Return all source document-links from the document.
  ///
  /// @Snippet(path: "DocumentLinkService_ListLinkedSources")
  public func listLinkedSources(
    request: ListLinkedSourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse {
    try await self.inner.listLinkedSources(request: request, options: options)
  }

  /// Create a link between a source document and a target document.
  ///
  /// @Snippet(path: "DocumentLinkService_CreateDocumentLink")
  public func createDocumentLink(
    request: CreateDocumentLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentLink {
    try await self.inner.createDocumentLink(request: request, options: options)
  }

  /// Remove the link between the source and target documents.
  ///
  /// @Snippet(path: "DocumentLinkService_DeleteDocumentLink")
  public func deleteDocumentLink(
    request: DeleteDocumentLinkRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDocumentLink(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentLinkService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DocumentLinkServiceClient`.
  ///
  /// To mock `DocumentLinkServiceClient` change your functions to receive
  /// `some DocumentLinkServiceProtocol` or `any DocumentLinkServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DocumentLinkServiceProtocol: Sendable {
    /// See `DocumentLinkServiceClient.listLinkedTargets`.
    func listLinkedTargets(
      request: ListLinkedTargetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse

    /// See `DocumentLinkServiceClient.listLinkedSources`.
    func listLinkedSources(
      request: ListLinkedSourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse

    /// See `DocumentLinkServiceClient.createDocumentLink`.
    func createDocumentLink(
      request: CreateDocumentLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentLink

    /// See `DocumentLinkServiceClient.deleteDocumentLink`.
    func deleteDocumentLink(
      request: DeleteDocumentLinkRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DocumentLinkServiceProtocol {
  public func listLinkedTargets(request: ListLinkedTargetsRequest) async throws
    -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse
  {
    try await self.listLinkedTargets(request: request, options: .init())
  }

  public func listLinkedTargets(
    request: ListLinkedTargetsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLinkedTargets(
    parent: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse {
    let request = ListLinkedTargetsRequest().with {
      $0.parent = parent
    }
    return try await self.listLinkedTargets(request: request)
  }

  public func listLinkedSources(request: ListLinkedSourcesRequest) async throws
    -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse
  {
    try await self.listLinkedSources(request: request, options: .init())
  }

  public func listLinkedSources(
    request: ListLinkedSourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLinkedSourcesByItems(
    request: ListLinkedSourcesRequest
  ) -> any AsyncSequence<DocumentLink, Swift.Error> & Sendable {
    self.listLinkedSourcesByItems(request: request, options: .init())
  }

  /// Return all source document-links from the document.
  ///
  /// @Snippet(path: "DocumentLinkService_ListLinkedSources")
  public func listLinkedSourcesByItems(
    request: ListLinkedSourcesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DocumentLink, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse in
      var request = request
      request.pageToken = token
      return try await self.listLinkedSources(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLinkedSourcesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<DocumentLink, Swift.Error> & Sendable {
    let request = ListLinkedSourcesRequest().with {
      $0.parent = parent
    }
    return self.listLinkedSourcesByItems(request: request)
  }

  public func createDocumentLink(request: CreateDocumentLinkRequest) async throws
    -> GoogleCloudContentWarehouseV1.DocumentLink
  {
    try await self.createDocumentLink(request: request, options: .init())
  }

  public func createDocumentLink(
    request: CreateDocumentLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentLink {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDocumentLink(
    parent: Swift.String,
    documentLink: DocumentLink?,
  ) async throws -> GoogleCloudContentWarehouseV1.DocumentLink {
    let request = CreateDocumentLinkRequest().with {
      $0.parent = parent
      $0.documentLink = documentLink
    }
    return try await self.createDocumentLink(request: request)
  }

  public func deleteDocumentLink(request: DeleteDocumentLinkRequest) async throws {
    try await self.deleteDocumentLink(request: request, options: .init())
  }

  public func deleteDocumentLink(
    request: DeleteDocumentLinkRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDocumentLink(
    name: Swift.String,
  ) async throws {
    let request = DeleteDocumentLinkRequest().with {
      $0.name = name
    }
    try await self.deleteDocumentLink(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
