// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudDocumentAIV1
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines the structure for content warehouse document proto.
public struct Document: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the document.
  /// Format:
  /// projects/{project_number}/locations/{location}/documents/{document_id}.
  ///
  /// The name is ignored when creating a document.
  public var name: Swift.String = Swift.String()

  /// The reference ID set by customers. Must be unique per project and location.
  public var referenceId: Swift.String = Swift.String()

  /// Required. Display name of the document given by the user. This name will be
  /// displayed in the UI. Customer can populate this field with the name of the
  /// document. This differs from the 'title' field as 'title' is optional and
  /// stores the top heading in the document.
  public var displayName: Swift.String = Swift.String()

  /// Title that describes the document.
  /// This can be the top heading or text that describes the document.
  public var title: Swift.String = Swift.String()

  /// Uri to display the document, for example, in the UI.
  public var displayUri: Swift.String = Swift.String()

  /// The Document schema name.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  public var documentSchemaName: Swift.String = Swift.String()

  /// A path linked to structured content file.
  @available(*, deprecated)
  public var structuredContentUri: Swift.String = Swift.String()

  /// List of values that are user supplied metadata.
  public var properties: [Property] = []

  /// Output only. The time when the document is last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the document is created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// This is used when DocAI was not used to load the document and parsing/
  /// extracting is needed for the inline_raw_document.  For example, if
  /// inline_raw_document is the byte representation of a PDF file, then
  /// this should be set to: RAW_DOCUMENT_FILE_TYPE_PDF.
  public var rawDocumentFileType: RawDocumentFileType = RawDocumentFileType()

  /// If true, makes the document visible to asynchronous policies and rules.
  @available(*, deprecated)
  public var asyncEnabled: Swift.Bool = Swift.Bool()

  /// Indicates the category (image, audio, video etc.) of the original content.
  public var contentCategory: ContentCategory = ContentCategory()

  /// If true, text extraction will not be performed.
  @available(*, deprecated)
  public var textExtractionDisabled: Swift.Bool = Swift.Bool()

  /// If true, text extraction will be performed.
  public var textExtractionEnabled: Swift.Bool = Swift.Bool()

  /// The user who creates the document.
  public var creator: Swift.String = Swift.String()

  /// The user who lastly updates the document.
  public var updater: Swift.String = Swift.String()

  /// Output only. If linked to a Collection with RetentionPolicy, the date when
  /// the document becomes mutable.
  public var dispositionTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Indicates if the document has a legal hold on it.
  public var legalHold: Swift.Bool = Swift.Bool()

  public var structuredContent: OneOf_StructuredContent? = nil

  /// Raw document file.
  public var rawDocument: OneOf_RawDocument? = nil

  /// Initialize a new instance of `Document`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Document().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case referenceId = "referenceId"
    case displayName = "displayName"
    case title = "title"
    case displayUri = "displayUri"
    case documentSchemaName = "documentSchemaName"
    case plainText = "plainText"
    case cloudAiDocument = "cloudAiDocument"
    case structuredContentUri = "structuredContentUri"
    case rawDocumentPath = "rawDocumentPath"
    case inlineRawDocument = "inlineRawDocument"
    case properties = "properties"
    case updateTime = "updateTime"
    case createTime = "createTime"
    case rawDocumentFileType = "rawDocumentFileType"
    case asyncEnabled = "asyncEnabled"
    case contentCategory = "contentCategory"
    case textExtractionDisabled = "textExtractionDisabled"
    case textExtractionEnabled = "textExtractionEnabled"
    case creator = "creator"
    case updater = "updater"
    case dispositionTime = "dispositionTime"
    case legalHold = "legalHold"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.referenceId = try container.decode(Swift.String.self, forKey: .referenceId)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.title = try container.decode(Swift.String.self, forKey: .title)
    self.displayUri = try container.decode(Swift.String.self, forKey: .displayUri)
    self.documentSchemaName = try container.decode(Swift.String.self, forKey: .documentSchemaName)
    self.structuredContentUri = try container.decode(
      Swift.String.self, forKey: .structuredContentUri)
    self.properties = try container.decode([Property].self, forKey: .properties)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.rawDocumentFileType = try container.decode(
      RawDocumentFileType.self, forKey: .rawDocumentFileType)
    self.asyncEnabled = try container.decode(Swift.Bool.self, forKey: .asyncEnabled)
    self.contentCategory = try container.decode(ContentCategory.self, forKey: .contentCategory)
    self.textExtractionDisabled = try container.decode(
      Swift.Bool.self, forKey: .textExtractionDisabled)
    self.textExtractionEnabled = try container.decode(
      Swift.Bool.self, forKey: .textExtractionEnabled)
    self.creator = try container.decode(Swift.String.self, forKey: .creator)
    self.updater = try container.decode(Swift.String.self, forKey: .updater)
    self.dispositionTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .dispositionTime)
    self.legalHold = try container.decode(Swift.Bool.self, forKey: .legalHold)

    var structuredContent: OneOf_StructuredContent? = nil
    let structuredContentCheckAndSet = {
      if structuredContent != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'structuredContent'"))
      }
      structuredContent = $0
    }
    if let plainText = try container.decodeIfPresent(Swift.String.self, forKey: .plainText) {
      try structuredContentCheckAndSet(.plainText(plainText))
    }
    if let cloudAiDocument = try container.decodeIfPresent(
      GoogleCloudDocumentAIV1.Document?.self, forKey: .cloudAiDocument)
    {
      try structuredContentCheckAndSet(.cloudAiDocument(cloudAiDocument))
    }
    self.structuredContent = structuredContent

    var rawDocument: OneOf_RawDocument? = nil
    let rawDocumentCheckAndSet = {
      if rawDocument != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'rawDocument'"))
      }
      rawDocument = $0
    }
    if let rawDocumentPath = try container.decodeIfPresent(
      Swift.String.self, forKey: .rawDocumentPath)
    {
      try rawDocumentCheckAndSet(.rawDocumentPath(rawDocumentPath))
    }
    if let inlineRawDocument = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .inlineRawDocument)
    {
      try rawDocumentCheckAndSet(.inlineRawDocument(inlineRawDocument))
    }
    self.rawDocument = rawDocument
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.referenceId, forKey: .referenceId)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.displayUri, forKey: .displayUri)
    try container.encode(self.documentSchemaName, forKey: .documentSchemaName)
    try container.encode(self.structuredContentUri, forKey: .structuredContentUri)
    try container.encode(self.properties, forKey: .properties)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.rawDocumentFileType, forKey: .rawDocumentFileType)
    try container.encode(self.asyncEnabled, forKey: .asyncEnabled)
    try container.encode(self.contentCategory, forKey: .contentCategory)
    try container.encode(self.textExtractionDisabled, forKey: .textExtractionDisabled)
    try container.encode(self.textExtractionEnabled, forKey: .textExtractionEnabled)
    try container.encode(self.creator, forKey: .creator)
    try container.encode(self.updater, forKey: .updater)
    try container.encode(self.dispositionTime, forKey: .dispositionTime)
    try container.encode(self.legalHold, forKey: .legalHold)

    if let choice = self.structuredContent {
      switch choice {
      case .plainText(let value):
        try container.encode(value, forKey: .plainText)
      case .cloudAiDocument(let value):
        try container.encode(value, forKey: .cloudAiDocument)
      }
    }

    if let choice = self.rawDocument {
      switch choice {
      case .rawDocumentPath(let value):
        try container.encode(value, forKey: .rawDocumentPath)
      case .inlineRawDocument(let value):
        try container.encode(value, forKey: .inlineRawDocument)
      }
    }
  }

  public enum OneOf_StructuredContent: Codable, Equatable, Sendable {
    /// Other document format, such as PPTX, XLXS
    case plainText(Swift.String)
    /// Document AI format to save the structured content, including OCR.
    indirect case cloudAiDocument(GoogleCloudDocumentAIV1.Document?)
  }

  /// Raw document file.
  public enum OneOf_RawDocument: Codable, Equatable, Sendable {
    /// Raw document file in Cloud Storage path.
    case rawDocumentPath(Swift.String)
    /// Raw document content.
    case inlineRawDocument(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.Document"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
