// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  final class DocumentLinkServiceRetry: DocumentLinkServiceStub {
    let inner: any DocumentLinkServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any DocumentLinkServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listLinkedTargets(
      request: ListLinkedTargetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ListLinkedTargetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.ListLinkedTargetsResponse
          in
          return try await self.inner.listLinkedTargets(request: r, options: o)
        })
    }

    public func listLinkedSources(
      request: ListLinkedSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ListLinkedSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.ListLinkedSourcesResponse
          in
          return try await self.inner.listLinkedSources(request: r, options: o)
        })
    }

    public func createDocumentLink(
      request: CreateDocumentLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.DocumentLink {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDocumentLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.DocumentLink
          in
          return try await self.inner.createDocumentLink(request: r, options: o)
        })
    }

    public func deleteDocumentLink(
      request: DeleteDocumentLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDocumentLinkRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDocumentLink(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
