// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A document schema used to define document structure.
public struct DocumentSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the document schema.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  ///
  /// The name is ignored when creating a document schema.
  public var name: Swift.String = Swift.String()

  /// Required. Name of the schema given by the user. Must be unique per project.
  public var displayName: Swift.String = Swift.String()

  /// Document details.
  public var propertyDefinitions: [PropertyDefinition] = []

  /// Document Type, true refers the document is a folder, otherwise it is
  /// a typical document.
  public var documentIsFolder: Swift.Bool = Swift.Bool()

  /// Output only. The time when the document schema is last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the document schema is created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Schema description.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `DocumentSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentSchema().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.DocumentSchema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
