// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The configuration of the Cloud Storage Ingestion pipeline.
public struct GcsIngestPipeline: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The input Cloud Storage folder. All files under this folder will be
  /// imported to Document Warehouse.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var inputPath: Swift.String = Swift.String()

  /// The Document Warehouse schema resource name. All documents processed by
  /// this pipeline will use this schema.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  public var schemaName: Swift.String = Swift.String()

  /// The Doc AI processor type name. Only used when the format of ingested
  /// files is Doc AI Document proto format.
  public var processorType: Swift.String = Swift.String()

  /// The flag whether to skip ingested documents.
  /// If it is set to true, documents in Cloud Storage contains key "status" with
  /// value "status=ingested" in custom metadata will be skipped to ingest.
  public var skipIngestedDocuments: Swift.Bool = Swift.Bool()

  /// Optional. The config for the Cloud Storage Ingestion pipeline.
  /// It provides additional customization options to run the pipeline and can be
  /// skipped if it is not applicable.
  public var pipelineConfig: IngestPipelineConfig? = nil

  /// Initialize a new instance of `GcsIngestPipeline`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsIngestPipeline().with { $0.inputPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.GcsIngestPipeline"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
