// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration of the Cloud Storage Ingestion pipeline.
public struct GcsIngestPipeline: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The input Cloud Storage folder. All files under this folder will be
  /// imported to Document Warehouse.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var inputPath: Swift.String = Swift.String()

  /// The Document Warehouse schema resource name. All documents processed by
  /// this pipeline will use this schema.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  public var schemaName: Swift.String = Swift.String()

  /// The Doc AI processor type name. Only used when the format of ingested
  /// files is Doc AI Document proto format.
  public var processorType: Swift.String = Swift.String()

  /// The flag whether to skip ingested documents.
  /// If it is set to true, documents in Cloud Storage contains key "status" with
  /// value "status=ingested" in custom metadata will be skipped to ingest.
  public var skipIngestedDocuments: Swift.Bool = Swift.Bool()

  /// Optional. The config for the Cloud Storage Ingestion pipeline.
  /// It provides additional customization options to run the pipeline and can be
  /// skipped if it is not applicable.
  public var pipelineConfig: IngestPipelineConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcsIngestPipeline`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsIngestPipeline().with { $0.inputPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputPath = CodingKeys(stringValue: "inputPath")
    static let schemaName = CodingKeys(stringValue: "schemaName")
    static let processorType = CodingKeys(stringValue: "processorType")
    static let skipIngestedDocuments = CodingKeys(stringValue: "skipIngestedDocuments")
    static let pipelineConfig = CodingKeys(stringValue: "pipelineConfig")

    static let _knownKeys: Set<Swift.String> = [
      "inputPath",
      "schemaName",
      "processorType",
      "skipIngestedDocuments",
      "pipelineConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputPath) {
      self.inputPath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schemaName) {
      self.schemaName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .processorType) {
      self.processorType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipIngestedDocuments) {
      self.skipIngestedDocuments = value
    }
    self.pipelineConfig = try container.decodeIfPresent(
      IngestPipelineConfig.self, forKey: .pipelineConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputPath, forKey: .inputPath)
    try container.encode(self.schemaName, forKey: .schemaName)
    try container.encode(self.processorType, forKey: .processorType)
    try container.encode(self.skipIngestedDocuments, forKey: .skipIngestedDocuments)
    try container.encodeIfPresent(self.pipelineConfig, forKey: .pipelineConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.GcsIngestPipeline"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
