// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The configuration of the Cloud Storage Ingestion with DocAI Processors
/// pipeline.
public struct GcsIngestWithDocAiProcessorsPipeline: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The input Cloud Storage folder. All files under this folder will be
  /// imported to Document Warehouse.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var inputPath: Swift.String = Swift.String()

  /// The split and classify processor information.
  /// The split and classify result will be used to find a matched extract
  /// processor.
  public var splitClassifyProcessorInfo: ProcessorInfo? = nil

  /// The extract processors information.
  /// One matched extract processor will be used to process documents based on
  /// the classify processor result. If no classify processor is specified, the
  /// first extract processor will be used.
  public var extractProcessorInfos: [ProcessorInfo] = []

  /// The Cloud Storage folder path used to store the raw results from
  /// processors.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var processorResultsFolderPath: Swift.String = Swift.String()

  /// The flag whether to skip ingested documents.
  /// If it is set to true, documents in Cloud Storage contains key "status" with
  /// value "status=ingested" in custom metadata will be skipped to ingest.
  public var skipIngestedDocuments: Swift.Bool = Swift.Bool()

  /// Optional. The config for the Cloud Storage Ingestion with DocAI Processors
  /// pipeline. It provides additional customization options to run the pipeline
  /// and can be skipped if it is not applicable.
  public var pipelineConfig: IngestPipelineConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcsIngestWithDocAiProcessorsPipeline`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsIngestWithDocAiProcessorsPipeline().with { $0.inputPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputPath = CodingKeys(stringValue: "inputPath")
    static let splitClassifyProcessorInfo = CodingKeys(stringValue: "splitClassifyProcessorInfo")
    static let extractProcessorInfos = CodingKeys(stringValue: "extractProcessorInfos")
    static let processorResultsFolderPath = CodingKeys(stringValue: "processorResultsFolderPath")
    static let skipIngestedDocuments = CodingKeys(stringValue: "skipIngestedDocuments")
    static let pipelineConfig = CodingKeys(stringValue: "pipelineConfig")

    static let _knownKeys: Set<Swift.String> = [
      "inputPath",
      "splitClassifyProcessorInfo",
      "extractProcessorInfos",
      "processorResultsFolderPath",
      "skipIngestedDocuments",
      "pipelineConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputPath) {
      self.inputPath = value
    }
    self.splitClassifyProcessorInfo = try container.decodeIfPresent(
      ProcessorInfo.self, forKey: .splitClassifyProcessorInfo)
    if let value = try container.decodeIfPresent(
      [ProcessorInfo].self, forKey: .extractProcessorInfos)
    {
      self.extractProcessorInfos = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .processorResultsFolderPath)
    {
      self.processorResultsFolderPath = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipIngestedDocuments) {
      self.skipIngestedDocuments = value
    }
    self.pipelineConfig = try container.decodeIfPresent(
      IngestPipelineConfig.self, forKey: .pipelineConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputPath, forKey: .inputPath)
    try container.encodeIfPresent(
      self.splitClassifyProcessorInfo, forKey: .splitClassifyProcessorInfo)
    try container.encode(self.extractProcessorInfos, forKey: .extractProcessorInfos)
    try container.encode(self.processorResultsFolderPath, forKey: .processorResultsFolderPath)
    try container.encode(self.skipIngestedDocuments, forKey: .skipIngestedDocuments)
    try container.encodeIfPresent(self.pipelineConfig, forKey: .pipelineConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.contentwarehouse.v1.GcsIngestWithDocAiProcessorsPipeline"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
