// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration of the Cloud Storage Ingestion with DocAI Processors
/// pipeline.
public struct GcsIngestWithDocAiProcessorsPipeline: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The input Cloud Storage folder. All files under this folder will be
  /// imported to Document Warehouse.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var inputPath: Swift.String = Swift.String()

  /// The split and classify processor information.
  /// The split and classify result will be used to find a matched extract
  /// processor.
  public var splitClassifyProcessorInfo: ProcessorInfo? = nil

  /// The extract processors information.
  /// One matched extract processor will be used to process documents based on
  /// the classify processor result. If no classify processor is specified, the
  /// first extract processor will be used.
  public var extractProcessorInfos: [ProcessorInfo] = []

  /// The Cloud Storage folder path used to store the raw results from
  /// processors.
  /// Format: `gs://<bucket-name>/<folder-name>`.
  public var processorResultsFolderPath: Swift.String = Swift.String()

  /// The flag whether to skip ingested documents.
  /// If it is set to true, documents in Cloud Storage contains key "status" with
  /// value "status=ingested" in custom metadata will be skipped to ingest.
  public var skipIngestedDocuments: Swift.Bool = Swift.Bool()

  /// Optional. The config for the Cloud Storage Ingestion with DocAI Processors
  /// pipeline. It provides additional customization options to run the pipeline
  /// and can be skipped if it is not applicable.
  public var pipelineConfig: IngestPipelineConfig? = nil

  /// Initialize a new instance of `GcsIngestWithDocAiProcessorsPipeline`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsIngestWithDocAiProcessorsPipeline().with { $0.inputPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.contentwarehouse.v1.GcsIngestWithDocAiProcessorsPipeline"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
