// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The histogram request.
public struct HistogramQuery: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// An expression specifies a histogram request against matching documents for
  /// searches.
  ///
  /// See
  /// [SearchDocumentsRequest.histogram_queries][google.cloud.contentwarehouse.v1.SearchDocumentsRequest.histogram_queries]
  /// for details about syntax.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest.histogram_queries]: <doc:SearchDocumentsRequest/histogramQueries>
  public var histogramQuery: Swift.String = Swift.String()

  /// Controls if the histogram query requires the return of a precise count.
  /// Enable this flag may adversely impact performance.
  ///
  /// Defaults to true.
  public var requirePreciseResultSize: Swift.Bool = Swift.Bool()

  /// Optional. Filter the result of histogram query by the property names. It
  /// only works with histogram query count('FilterableProperties'). It is an
  /// optional. It will perform histogram on all the property names for all the
  /// document schemas. Setting this field will have a better performance.
  public var filters: HistogramQueryPropertyNameFilter? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HistogramQuery`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HistogramQuery().with { $0.histogramQuery = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let histogramQuery = CodingKeys(stringValue: "histogramQuery")
    static let requirePreciseResultSize = CodingKeys(stringValue: "requirePreciseResultSize")
    static let filters = CodingKeys(stringValue: "filters")

    static let _knownKeys: Set<Swift.String> = [
      "histogramQuery",
      "requirePreciseResultSize",
      "filters",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .histogramQuery) {
      self.histogramQuery = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requirePreciseResultSize)
    {
      self.requirePreciseResultSize = value
    }
    self.filters = try container.decodeIfPresent(
      HistogramQueryPropertyNameFilter.self, forKey: .filters)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.histogramQuery, forKey: .histogramQuery)
    try container.encode(self.requirePreciseResultSize, forKey: .requirePreciseResultSize)
    try container.encodeIfPresent(self.filters, forKey: .filters)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.HistogramQuery"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
