// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

public struct HistogramQueryPropertyNameFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// This filter specifies the exact document schema(s)
  /// [Document.document_schema_name][google.cloud.contentwarehouse.v1.Document.document_schema_name]
  /// to run histogram query against. It is optional. It will perform histogram
  /// for property names for all the document schemas if it is not set.
  ///
  /// At most 10 document schema names are allowed.
  /// Format:
  /// projects/{project_number}/locations/{location}/documentSchemas/{document_schema_id}.
  ///
  /// [google.cloud.contentwarehouse.v1.Document.document_schema_name]: <doc:Document/documentSchemaName>
  public var documentSchemas: [Swift.String] = []

  /// It is optional. It will perform histogram for all the property names if it
  /// is not set.
  /// The properties need to be defined with the is_filterable flag set to
  /// true and the name of the property should be in the format:
  /// "schemaId.propertyName". The property needs to be defined in the schema.
  /// Example: the schema id is abc. Then the name of property for property
  /// MORTGAGE_TYPE will be "abc.MORTGAGE_TYPE".
  public var propertyNames: [Swift.String] = []

  /// By default, the y_axis is HISTOGRAM_YAXIS_DOCUMENT if this field is not
  /// set.
  public var yAxis: HistogramQueryPropertyNameFilter.HistogramYAxis =
    HistogramQueryPropertyNameFilter.HistogramYAxis()

  /// Initialize a new instance of `HistogramQueryPropertyNameFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HistogramQueryPropertyNameFilter().with { $0.documentSchemas = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The result of the histogram query count('FilterableProperties') using
  /// HISTOGRAM_YAXIS_DOCUMENT will be:
  /// invoice_id: 2
  /// address: 1
  /// payment_method: 2
  /// line_item_description: 1
  public enum HistogramYAxis: Codable, Equatable, Sendable {
    /// Count the documents per property name.
    case histogramYaxisDocument
    /// Count the properties per property name.
    case histogramYaxisProperty
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .histogramYaxisDocument
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .histogramYaxisDocument: return 0
      case .histogramYaxisProperty: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .histogramYaxisDocument: return "HISTOGRAM_YAXIS_DOCUMENT"
      case .histogramYaxisProperty: return "HISTOGRAM_YAXIS_PROPERTY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HistogramYAxis/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HISTOGRAM_YAXIS_DOCUMENT": self = .histogramYaxisDocument
      case "HISTOGRAM_YAXIS_PROPERTY": self = .histogramYaxisProperty
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HistogramYAxis/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .histogramYaxisDocument
      case 1: self = .histogramYaxisProperty
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .histogramYaxisDocument: return try container.encode(0)
      case .histogramYaxisProperty: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.HistogramQueryPropertyNameFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
