// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleIAMV1

/// The ingestion pipeline config.
public struct IngestPipelineConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The document level acl policy config.
  /// This refers to an Identity and Access (IAM) policy, which specifies access
  /// controls for all documents ingested by the pipeline. The
  /// [role][google.iam.v1.Binding.role] and
  /// [members][google.iam.v1.Binding.role] under the policy needs to be
  /// specified.
  ///
  /// The following roles are supported for document level acl control:
  /// * roles/contentwarehouse.documentAdmin
  /// * roles/contentwarehouse.documentEditor
  /// * roles/contentwarehouse.documentViewer
  ///
  /// The following members are supported for document level acl control:
  /// * user:user-email@example.com
  /// * group:group-email@example.com
  /// Note that for documents searched with LLM, only single level user or group
  /// acl check is supported.
  ///
  /// [google.iam.v1.Binding.role]: https://www.google.com/search?q=Swift+google.iam.v1+GoogleIAMV1.Binding/role
  public var documentAclPolicy: GoogleIAMV1.Policy? = nil

  /// The document text extraction enabled flag.
  /// If the flag is set to true, DWH will perform text extraction on the raw
  /// document.
  public var enableDocumentTextExtraction: Swift.Bool = Swift.Bool()

  /// Optional. The name of the folder to which all ingested documents will be
  /// linked during ingestion process. Format is
  /// `projects/{project}/locations/{location}/documents/{folder_id}`
  public var folder: Swift.String = Swift.String()

  /// The Cloud Function resource name. The Cloud Function needs to live inside
  /// consumer project and is accessible to Document AI Warehouse P4SA.
  /// Only Cloud Functions V2 is supported. Cloud function execution should
  /// complete within 5 minutes or this file ingestion may fail due to timeout.
  /// Format: `https://{region}-{project_id}.cloudfunctions.net/{cloud_function}`
  /// The following keys are available the request json payload.
  /// * display_name
  /// * properties
  /// * plain_text
  /// * reference_id
  /// * document_schema_name
  /// * raw_document_path
  /// * raw_document_file_type
  ///
  /// The following keys from the cloud function json response payload will be
  /// ingested to the Document AI Warehouse as part of Document proto content
  /// and/or related information. The original values will be overridden if any
  /// key is present in the response.
  /// * display_name
  /// * properties
  /// * plain_text
  /// * document_acl_policy
  /// * folder
  public var cloudFunction: Swift.String = Swift.String()

  /// Initialize a new instance of `IngestPipelineConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IngestPipelineConfig().with { $0.documentAclPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.IngestPipelineConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
