// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Options for merging updated fields.
public struct MergeFieldsOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// When merging message fields, the default behavior is to merge
  /// the content of two message fields together. If you instead want to use
  /// the field from the source message to replace the corresponding field in
  /// the destination message, set this flag to true. When this flag is set,
  /// specified submessage fields that are missing in source will be cleared in
  /// destination.
  public var replaceMessageFields: Swift.Bool? = nil

  /// When merging repeated fields, the default behavior is to append
  /// entries from the source repeated field to the destination repeated field.
  /// If you instead want to keep only the entries from the source repeated
  /// field, set this flag to true.
  ///
  /// If you want to replace a repeated field within a message field on the
  /// destination message, you must set both replace_repeated_fields and
  /// replace_message_fields to true, otherwise the repeated fields will be
  /// appended.
  public var replaceRepeatedFields: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MergeFieldsOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MergeFieldsOptions().with { $0.replaceMessageFields = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let replaceMessageFields = CodingKeys(stringValue: "replaceMessageFields")
    static let replaceRepeatedFields = CodingKeys(stringValue: "replaceRepeatedFields")

    static let _knownKeys: Set<Swift.String> = [
      "replaceMessageFields",
      "replaceRepeatedFields",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.replaceMessageFields = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .replaceMessageFields)
    self.replaceRepeatedFields = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .replaceRepeatedFields)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.replaceMessageFields, forKey: .replaceMessageFields)
    try container.encodeIfPresent(self.replaceRepeatedFields, forKey: .replaceRepeatedFields)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.MergeFieldsOptions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
