// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// This service lets you manage pipelines.
///
/// @Snippet(path: "PipelineServiceQuickstart")
public class PipelineServiceClient: Clients.PipelineServiceProtocol {
  let inner: any Clients.PipelineServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `PipelineServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.PipelineServiceStub = try Clients.PipelineServiceTransport(options)
    inner = Clients.PipelineServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PipelineServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Run a predefined pipeline.
  ///
  /// @Snippet(path: "PipelineService_RunPipeline")
  public func runPipeline(
    request: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.runPipeline(request: request, options: options)
  }

  /// Run a predefined pipeline.
  ///
  /// @Snippet(path: "PipelineService_RunPipeline")
  public func runPipeline(
    withPolling: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<RunPipelineResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<RunPipelineResponse>.State in
      return try op._extractStatus(RunPipelineResponse.self)
    }
    let rawOp = try await self.runPipeline(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<RunPipelineResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PipelineService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PipelineServiceClient`.
  ///
  /// To mock `PipelineServiceClient` change your functions to receive
  /// `some PipelineServiceProtocol` or `any PipelineServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PipelineServiceProtocol {
    /// See `PipelineServiceClient.runPipeline`.
    func runPipeline(request: RunPipelineRequest) async throws -> GoogleLongRunning.Operation

    /// See `PipelineServiceClient.runPipeline`.
    func runPipeline(withPolling: RunPipelineRequest) async throws -> any GoogleCloudGax
      .PollableOperation<RunPipelineResponse>

    /// See `PipelineServiceClient.runPipeline`.
    func runPipeline(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<RunPipelineResponse>

    /// See `PipelineServiceClient.runPipeline`.
    func runPipeline(
      request: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PipelineServiceClient.runPipeline`.
    func runPipeline(
      withPolling: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<RunPipelineResponse>
  }
}

// Default implementations
extension Clients.PipelineServiceProtocol {
  public func runPipeline(request: RunPipelineRequest) async throws -> GoogleLongRunning.Operation {
    try await self.runPipeline(request: request, options: .init())
  }

  public func runPipeline(
    request: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runPipeline(withPolling: RunPipelineRequest) async throws -> any GoogleCloudGax
    .PollableOperation<RunPipelineResponse>
  {
    try await self.runPipeline(withPolling: withPolling, options: .init())
  }

  public func runPipeline(
    withPolling: RunPipelineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<RunPipelineResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<RunPipelineResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func runPipeline(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<RunPipelineResponse> {
    let request = RunPipelineRequest().with {
      $0.name = name
    }
    return try await self.runPipeline(withPolling: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
