// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Property of a document.
public struct Property: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Must match the name of a PropertyDefinition in the
  /// DocumentSchema.
  public var name: Swift.String = Swift.String()

  /// Type of the property.
  /// Must match the property_options type of the matching PropertyDefinition.
  /// Value of the Property parsed into a specific data type.
  /// Specific type value(s) obtained from Document AIs Property.mention_text
  /// field.
  public var values: OneOf_Values? = nil

  /// Initialize a new instance of `Property`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Property().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case integerValues = "integerValues"
    case floatValues = "floatValues"
    case textValues = "textValues"
    case enumValues = "enumValues"
    case propertyValues = "propertyValues"
    case dateTimeValues = "dateTimeValues"
    case mapProperty = "mapProperty"
    case timestampValues = "timestampValues"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var values: OneOf_Values? = nil
    let valuesCheckAndSet = {
      if values != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'values'"))
      }
      values = $0
    }
    if let integerValues = try container.decodeIfPresent(IntegerArray?.self, forKey: .integerValues)
    {
      try valuesCheckAndSet(.integerValues(integerValues))
    }
    if let floatValues = try container.decodeIfPresent(FloatArray?.self, forKey: .floatValues) {
      try valuesCheckAndSet(.floatValues(floatValues))
    }
    if let textValues = try container.decodeIfPresent(TextArray?.self, forKey: .textValues) {
      try valuesCheckAndSet(.textValues(textValues))
    }
    if let enumValues = try container.decodeIfPresent(EnumArray?.self, forKey: .enumValues) {
      try valuesCheckAndSet(.enumValues(enumValues))
    }
    if let propertyValues = try container.decodeIfPresent(
      PropertyArray?.self, forKey: .propertyValues)
    {
      try valuesCheckAndSet(.propertyValues(propertyValues))
    }
    if let dateTimeValues = try container.decodeIfPresent(
      DateTimeArray?.self, forKey: .dateTimeValues)
    {
      try valuesCheckAndSet(.dateTimeValues(dateTimeValues))
    }
    if let mapProperty = try container.decodeIfPresent(MapProperty?.self, forKey: .mapProperty) {
      try valuesCheckAndSet(.mapProperty(mapProperty))
    }
    if let timestampValues = try container.decodeIfPresent(
      TimestampArray?.self, forKey: .timestampValues)
    {
      try valuesCheckAndSet(.timestampValues(timestampValues))
    }
    self.values = values
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.values {
      switch choice {
      case .integerValues(let value):
        try container.encode(value, forKey: .integerValues)
      case .floatValues(let value):
        try container.encode(value, forKey: .floatValues)
      case .textValues(let value):
        try container.encode(value, forKey: .textValues)
      case .enumValues(let value):
        try container.encode(value, forKey: .enumValues)
      case .propertyValues(let value):
        try container.encode(value, forKey: .propertyValues)
      case .dateTimeValues(let value):
        try container.encode(value, forKey: .dateTimeValues)
      case .mapProperty(let value):
        try container.encode(value, forKey: .mapProperty)
      case .timestampValues(let value):
        try container.encode(value, forKey: .timestampValues)
      }
    }
  }

  /// Type of the property.
  /// Must match the property_options type of the matching PropertyDefinition.
  /// Value of the Property parsed into a specific data type.
  /// Specific type value(s) obtained from Document AIs Property.mention_text
  /// field.
  public enum OneOf_Values: Codable, Equatable, Sendable {
    /// Integer property values.
    indirect case integerValues(IntegerArray?)
    /// Float property values.
    indirect case floatValues(FloatArray?)
    /// String/text property values.
    indirect case textValues(TextArray?)
    /// Enum property values.
    indirect case enumValues(EnumArray?)
    /// Nested structured data property values.
    indirect case propertyValues(PropertyArray?)
    /// Date time property values.
    /// It is not supported by CMEK compliant deployment.
    indirect case dateTimeValues(DateTimeArray?)
    /// Map property values.
    indirect case mapProperty(MapProperty?)
    /// Timestamp property values.
    /// It is not supported by CMEK compliant deployment.
    indirect case timestampValues(TimestampArray?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.Property"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
