// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Additional result info for the question-answering feature.
public struct QAResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Highlighted sections in the snippet.
  public var highlights: [QAResult.Highlight] = []

  /// The calibrated confidence score for this document, in the range
  /// [0., 1.]. This represents the confidence level for whether the returned
  /// document and snippet answers the user's query.
  public var confidenceScore: Swift.Float = Swift.Float()

  /// Initialize a new instance of `QAResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QAResult().with { $0.highlights = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A text span in the search text snippet that represents a highlighted
  /// section (answer context, highly relevant sentence, etc.).
  public struct Highlight: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Start index of the highlight.
    public var startIndex: Swift.Int32 = Swift.Int32()

    /// End index of the highlight, exclusive.
    public var endIndex: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Highlight`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Highlight().with { $0.startIndex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.contentwarehouse.v1.QAResult.Highlight"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.QAResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
