// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class RuleSetServiceRetry: RuleSetServiceStub {
    let inner: any RuleSetServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any RuleSetServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createRuleSet(
      request: CreateRuleSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateRuleSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.RuleSet
          in
          return try await self.inner.createRuleSet(request: r, options: o)
        })
    }

    public func getRuleSet(
      request: GetRuleSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRuleSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.RuleSet
          in
          return try await self.inner.getRuleSet(request: r, options: o)
        })
    }

    public func updateRuleSet(
      request: UpdateRuleSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateRuleSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.RuleSet
          in
          return try await self.inner.updateRuleSet(request: r, options: o)
        })
    }

    public func deleteRuleSet(
      request: DeleteRuleSetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteRuleSetRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteRuleSet(request: r, options: o)
        })
    }

    public func listRuleSets(
      request: ListRuleSetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListRuleSetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse
          in
          return try await self.inner.listRuleSets(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
