// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents the rule for a content warehouse trigger.
public struct Rule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Short description of the rule and its context.
  public var description: Swift.String = Swift.String()

  /// ID of the rule. It has to be unique across all the examples.
  /// This is managed internally.
  public var ruleId: Swift.String = Swift.String()

  /// Identifies the trigger type for running the policy.
  public var triggerType: Rule.TriggerType = Rule.TriggerType()

  /// Represents the conditional expression to be evaluated.
  /// Expression should evaluate to a boolean result.
  /// When the condition is true actions are executed.
  /// Example: user_role = "hsbc_role_1" AND doc.salary > 20000
  public var condition: Swift.String = Swift.String()

  /// List of actions that are executed when the rule is satisfied.
  public var actions: [Action] = []

  /// Initialize a new instance of `Rule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rule().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The trigger types for actions.
  public enum TriggerType: Codable, Equatable, Sendable {
    /// Trigger for unknown action.
    case unknown
    /// Trigger for create document action.
    case onCreate
    /// Trigger for update document action.
    case onUpdate
    /// Trigger for create link action.
    case onCreateLink
    /// Trigger for delete link action.
    case onDeleteLink
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .onCreate: return 1
      case .onUpdate: return 4
      case .onCreateLink: return 7
      case .onDeleteLink: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .onCreate: return "ON_CREATE"
      case .onUpdate: return "ON_UPDATE"
      case .onCreateLink: return "ON_CREATE_LINK"
      case .onDeleteLink: return "ON_DELETE_LINK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TriggerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "ON_CREATE": self = .onCreate
      case "ON_UPDATE": self = .onUpdate
      case "ON_CREATE_LINK": self = .onCreateLink
      case "ON_DELETE_LINK": self = .onDeleteLink
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TriggerType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .onCreate
      case 4: self = .onUpdate
      case 7: self = .onCreateLink
      case 8: self = .onDeleteLink
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .onCreate: return try container.encode(1)
      case .onUpdate: return try container.encode(4)
      case .onCreateLink: return try container.encode(7)
      case .onDeleteLink: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.Rule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
