// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// Service to manage customer specific RuleSets.
///
/// @Snippet(path: "RuleSetServiceQuickstart")
public final class RuleSetServiceClient: Clients.RuleSetServiceProtocol, Sendable {
  let inner: any Clients.RuleSetServiceStub

  /// Creates a new `RuleSetServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.RuleSetServiceStub = try Clients.RuleSetServiceTransport(options)
    inner = Clients.RuleSetServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RuleSetServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a ruleset.
  ///
  /// @Snippet(path: "RuleSetService_CreateRuleSet")
  public func createRuleSet(
    request: CreateRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    try await self.inner.createRuleSet(request: request, options: options)
  }

  /// Gets a ruleset. Returns NOT_FOUND if the ruleset does not exist.
  ///
  /// @Snippet(path: "RuleSetService_GetRuleSet")
  public func getRuleSet(
    request: GetRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    try await self.inner.getRuleSet(request: request, options: options)
  }

  /// Updates a ruleset. Returns INVALID_ARGUMENT if the name of the ruleset
  /// is non-empty and does not equal the existing name.
  ///
  /// @Snippet(path: "RuleSetService_UpdateRuleSet")
  public func updateRuleSet(
    request: UpdateRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    try await self.inner.updateRuleSet(request: request, options: options)
  }

  /// Deletes a ruleset. Returns NOT_FOUND if the document does not exist.
  ///
  /// @Snippet(path: "RuleSetService_DeleteRuleSet")
  public func deleteRuleSet(
    request: DeleteRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteRuleSet(request: request, options: options)
  }

  /// Lists rulesets.
  ///
  /// @Snippet(path: "RuleSetService_ListRuleSets")
  public func listRuleSets(
    request: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse {
    try await self.inner.listRuleSets(request: request, options: options)
  }

  /// Lists rulesets.
  ///
  /// @Snippet(path: "RuleSetService_ListRuleSets")
  public func listRuleSets(
    byItem: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<RuleSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listRuleSets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RuleSetService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RuleSetServiceClient`.
  ///
  /// To mock `RuleSetServiceClient` change your functions to receive
  /// `some RuleSetServiceProtocol` or `any RuleSetServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RuleSetServiceProtocol {
    /// See `RuleSetServiceClient.createRuleSet`.
    func createRuleSet(request: CreateRuleSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.createRuleSet`.
    func createRuleSet(
      parent: Swift.String,
      ruleSet: RuleSet?,
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.getRuleSet`.
    func getRuleSet(request: GetRuleSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.getRuleSet`.
    func getRuleSet(
      name: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.updateRuleSet`.
    func updateRuleSet(request: UpdateRuleSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.updateRuleSet`.
    func updateRuleSet(
      name: Swift.String,
      ruleSet: RuleSet?,
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.deleteRuleSet`.
    func deleteRuleSet(request: DeleteRuleSetRequest) async throws

    /// See `RuleSetServiceClient.deleteRuleSet`.
    func deleteRuleSet(
      name: Swift.String,
    ) async throws

    /// See `RuleSetServiceClient.listRuleSets`.
    func listRuleSets(request: ListRuleSetsRequest) async throws
      -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse

    /// See `RuleSetServiceClient.listRuleSets`.
    func listRuleSets(
      byItem: ListRuleSetsRequest
    ) throws -> any AsyncSequence<RuleSet, Swift.Error>

    /// See `RuleSetServiceClient.listRuleSets`.
    func listRuleSets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<RuleSet, Swift.Error>

    /// See `RuleSetServiceClient.createRuleSet`.
    func createRuleSet(
      request: CreateRuleSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.getRuleSet`.
    func getRuleSet(
      request: GetRuleSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.updateRuleSet`.
    func updateRuleSet(
      request: UpdateRuleSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.RuleSet

    /// See `RuleSetServiceClient.deleteRuleSet`.
    func deleteRuleSet(
      request: DeleteRuleSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RuleSetServiceClient.listRuleSets`.
    func listRuleSets(
      request: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse

    /// See `RuleSetServiceClient.listRuleSets`.
    func listRuleSets(
      byItem: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<RuleSet, Swift.Error>
  }
}

// Default implementations
extension Clients.RuleSetServiceProtocol {
  public func createRuleSet(request: CreateRuleSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.RuleSet
  {
    try await self.createRuleSet(request: request, options: .init())
  }

  public func createRuleSet(
    request: CreateRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createRuleSet(
    parent: Swift.String,
    ruleSet: RuleSet?,
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    let request = CreateRuleSetRequest().with {
      $0.parent = parent
      $0.ruleSet = ruleSet
    }
    return try await self.createRuleSet(request: request)
  }

  public func getRuleSet(request: GetRuleSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.RuleSet
  {
    try await self.getRuleSet(request: request, options: .init())
  }

  public func getRuleSet(
    request: GetRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRuleSet(
    name: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    let request = GetRuleSetRequest().with {
      $0.name = name
    }
    return try await self.getRuleSet(request: request)
  }

  public func updateRuleSet(request: UpdateRuleSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.RuleSet
  {
    try await self.updateRuleSet(request: request, options: .init())
  }

  public func updateRuleSet(
    request: UpdateRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateRuleSet(
    name: Swift.String,
    ruleSet: RuleSet?,
  ) async throws -> GoogleCloudContentWarehouseV1.RuleSet {
    let request = UpdateRuleSetRequest().with {
      $0.name = name
      $0.ruleSet = ruleSet
    }
    return try await self.updateRuleSet(request: request)
  }

  public func deleteRuleSet(request: DeleteRuleSetRequest) async throws {
    try await self.deleteRuleSet(request: request, options: .init())
  }

  public func deleteRuleSet(
    request: DeleteRuleSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteRuleSet(
    name: Swift.String,
  ) async throws {
    let request = DeleteRuleSetRequest().with {
      $0.name = name
    }
    try await self.deleteRuleSet(request: request)
  }

  public func listRuleSets(request: ListRuleSetsRequest) async throws
    -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse
  {
    try await self.listRuleSets(request: request, options: .init())
  }

  public func listRuleSets(
    request: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRuleSets(
    byItem: ListRuleSetsRequest
  ) throws -> any AsyncSequence<RuleSet, Swift.Error> {
    try self.listRuleSets(byItem: byItem, options: .init())
  }

  public func listRuleSets(
    byItem: ListRuleSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<RuleSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.ListRuleSetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRuleSets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<RuleSet, Swift.Error> {
    let request = ListRuleSetsRequest().with {
      $0.parent = parent
    }
    return try self.listRuleSets(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
