// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Records the output of Rule Engine including rule evaluation and actions
/// result.
public struct RuleEngineOutput: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the document against which the rules and actions were evaluated.
  public var documentName: Swift.String = Swift.String()

  /// Output from Rule Evaluator containing matched, unmatched and invalid rules.
  public var ruleEvaluatorOutput: RuleEvaluatorOutput? = nil

  /// Output from Action Executor containing rule and corresponding actions
  /// execution result.
  public var actionExecutorOutput: ActionExecutorOutput? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuleEngineOutput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuleEngineOutput().with { $0.documentName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let documentName = CodingKeys(stringValue: "documentName")
    static let ruleEvaluatorOutput = CodingKeys(stringValue: "ruleEvaluatorOutput")
    static let actionExecutorOutput = CodingKeys(stringValue: "actionExecutorOutput")

    static let _knownKeys: Set<Swift.String> = [
      "documentName",
      "ruleEvaluatorOutput",
      "actionExecutorOutput",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .documentName) {
      self.documentName = value
    }
    self.ruleEvaluatorOutput = try container.decodeIfPresent(
      RuleEvaluatorOutput.self, forKey: .ruleEvaluatorOutput)
    self.actionExecutorOutput = try container.decodeIfPresent(
      ActionExecutorOutput.self, forKey: .actionExecutorOutput)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.documentName, forKey: .documentName)
    try container.encodeIfPresent(self.ruleEvaluatorOutput, forKey: .ruleEvaluatorOutput)
    try container.encodeIfPresent(self.actionExecutorOutput, forKey: .actionExecutorOutput)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.RuleEngineOutput"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
