// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents the output of the Rule Evaluator.
public struct RuleEvaluatorOutput: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// List of rules fetched from database for the given request trigger type.
  public var triggeredRules: [Rule] = []

  /// A subset of triggered rules that are evaluated true for a given request.
  public var matchedRules: [Rule] = []

  /// A subset of triggered rules that failed the validation check(s) after
  /// parsing.
  public var invalidRules: [InvalidRule] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuleEvaluatorOutput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuleEvaluatorOutput().with { $0.triggeredRules = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let triggeredRules = CodingKeys(stringValue: "triggeredRules")
    static let matchedRules = CodingKeys(stringValue: "matchedRules")
    static let invalidRules = CodingKeys(stringValue: "invalidRules")

    static let _knownKeys: Set<Swift.String> = [
      "triggeredRules",
      "matchedRules",
      "invalidRules",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Rule].self, forKey: .triggeredRules) {
      self.triggeredRules = value
    }
    if let value = try container.decodeIfPresent([Rule].self, forKey: .matchedRules) {
      self.matchedRules = value
    }
    if let value = try container.decodeIfPresent([InvalidRule].self, forKey: .invalidRules) {
      self.invalidRules = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.triggeredRules, forKey: .triggeredRules)
    try container.encode(self.matchedRules, forKey: .matchedRules)
    try container.encode(self.invalidRules, forKey: .invalidRules)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.RuleEvaluatorOutput"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
