// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata message of RunPipeline method.
public struct RunPipelineMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Number of files that were processed by the pipeline.
  public var totalFileCount: Swift.Int32 = Swift.Int32()

  /// Number of files that have failed at some point in the pipeline.
  public var failedFileCount: Swift.Int32 = Swift.Int32()

  /// User unique identification and groups information.
  public var userInfo: UserInfo? = nil

  /// The list of response details of each document.
  public var individualDocumentStatuses: [RunPipelineMetadata.IndividualDocumentStatus] = []

  /// The pipeline metadata.
  public var pipelineMetadata: OneOf_PipelineMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RunPipelineMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RunPipelineMetadata().with { $0.totalFileCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let totalFileCount = CodingKeys(stringValue: "totalFileCount")
    static let failedFileCount = CodingKeys(stringValue: "failedFileCount")
    static let userInfo = CodingKeys(stringValue: "userInfo")
    static let gcsIngestPipelineMetadata = CodingKeys(stringValue: "gcsIngestPipelineMetadata")
    static let exportToCdwPipelineMetadata = CodingKeys(stringValue: "exportToCdwPipelineMetadata")
    static let processWithDocAiPipelineMetadata = CodingKeys(
      stringValue: "processWithDocAiPipelineMetadata")
    static let individualDocumentStatuses = CodingKeys(stringValue: "individualDocumentStatuses")

    static let _knownKeys: Set<Swift.String> = [
      "totalFileCount",
      "failedFileCount",
      "userInfo",
      "gcsIngestPipelineMetadata",
      "exportToCdwPipelineMetadata",
      "processWithDocAiPipelineMetadata",
      "individualDocumentStatuses",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalFileCount) {
      self.totalFileCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .failedFileCount) {
      self.failedFileCount = value
    }
    self.userInfo = try container.decodeIfPresent(UserInfo.self, forKey: .userInfo)
    if let value = try container.decodeIfPresent(
      [RunPipelineMetadata.IndividualDocumentStatus].self, forKey: .individualDocumentStatuses)
    {
      self.individualDocumentStatuses = value
    }

    var pipelineMetadata: OneOf_PipelineMetadata? = nil
    let pipelineMetadataCheckAndSet = {
      if pipelineMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pipelineMetadata'"))
      }
      pipelineMetadata = $0
    }
    if let gcsIngestPipelineMetadata = try container.decodeIfPresent(
      RunPipelineMetadata.GcsIngestPipelineMetadata?.self, forKey: .gcsIngestPipelineMetadata)
    {
      try pipelineMetadataCheckAndSet(.gcsIngestPipelineMetadata(gcsIngestPipelineMetadata))
    }
    if let exportToCdwPipelineMetadata = try container.decodeIfPresent(
      RunPipelineMetadata.ExportToCdwPipelineMetadata?.self, forKey: .exportToCdwPipelineMetadata)
    {
      try pipelineMetadataCheckAndSet(.exportToCdwPipelineMetadata(exportToCdwPipelineMetadata))
    }
    if let processWithDocAiPipelineMetadata = try container.decodeIfPresent(
      RunPipelineMetadata.ProcessWithDocAiPipelineMetadata?.self,
      forKey: .processWithDocAiPipelineMetadata)
    {
      try pipelineMetadataCheckAndSet(
        .processWithDocAiPipelineMetadata(processWithDocAiPipelineMetadata))
    }
    self.pipelineMetadata = pipelineMetadata
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.totalFileCount, forKey: .totalFileCount)
    try container.encode(self.failedFileCount, forKey: .failedFileCount)
    try container.encodeIfPresent(self.userInfo, forKey: .userInfo)
    try container.encode(self.individualDocumentStatuses, forKey: .individualDocumentStatuses)

    if let choice = self.pipelineMetadata {
      switch choice {
      case .gcsIngestPipelineMetadata(let value):
        try container.encode(value, forKey: .gcsIngestPipelineMetadata)
      case .exportToCdwPipelineMetadata(let value):
        try container.encode(value, forKey: .exportToCdwPipelineMetadata)
      case .processWithDocAiPipelineMetadata(let value):
        try container.encode(value, forKey: .processWithDocAiPipelineMetadata)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The metadata message for GcsIngest pipeline.
  public struct GcsIngestPipelineMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The input Cloud Storage folder in this pipeline.
    /// Format: `gs://<bucket-name>/<folder-name>`.
    public var inputPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GcsIngestPipelineMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsIngestPipelineMetadata().with { $0.inputPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputPath = CodingKeys(stringValue: "inputPath")

      static let _knownKeys: Set<Swift.String> = [
        "inputPath"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputPath) {
        self.inputPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputPath, forKey: .inputPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineMetadata.GcsIngestPipelineMetadata"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The metadata message for Export-to-CDW pipeline.
  public struct ExportToCdwPipelineMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The input list of all the resource names of the documents to be exported.
    public var documents: [Swift.String] = []

    /// The output CDW dataset resource name.
    public var docAiDataset: Swift.String = Swift.String()

    /// The output Cloud Storage folder in this pipeline.
    public var outputPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExportToCdwPipelineMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportToCdwPipelineMetadata().with { $0.documents = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let documents = CodingKeys(stringValue: "documents")
      static let docAiDataset = CodingKeys(stringValue: "docAiDataset")
      static let outputPath = CodingKeys(stringValue: "outputPath")

      static let _knownKeys: Set<Swift.String> = [
        "documents",
        "docAiDataset",
        "outputPath",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .documents) {
        self.documents = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .docAiDataset) {
        self.docAiDataset = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputPath) {
        self.outputPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.documents, forKey: .documents)
      try container.encode(self.docAiDataset, forKey: .docAiDataset)
      try container.encode(self.outputPath, forKey: .outputPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineMetadata.ExportToCdwPipelineMetadata"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The metadata message for Process-with-DocAi pipeline.
  public struct ProcessWithDocAiPipelineMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The input list of all the resource names of the documents to be
    /// processed.
    public var documents: [Swift.String] = []

    /// The DocAI processor to process the documents with.
    public var processorInfo: ProcessorInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProcessWithDocAiPipelineMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProcessWithDocAiPipelineMetadata().with { $0.documents = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let documents = CodingKeys(stringValue: "documents")
      static let processorInfo = CodingKeys(stringValue: "processorInfo")

      static let _knownKeys: Set<Swift.String> = [
        "documents",
        "processorInfo",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .documents) {
        self.documents = value
      }
      self.processorInfo = try container.decodeIfPresent(ProcessorInfo.self, forKey: .processorInfo)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.documents, forKey: .documents)
      try container.encodeIfPresent(self.processorInfo, forKey: .processorInfo)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineMetadata.ProcessWithDocAiPipelineMetadata"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The status of processing a document.
  public struct IndividualDocumentStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Document identifier of an existing document.
    public var documentId: Swift.String = Swift.String()

    /// The status processing the document.
    public var status: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IndividualDocumentStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IndividualDocumentStatus().with { $0.documentId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let documentId = CodingKeys(stringValue: "documentId")
      static let status = CodingKeys(stringValue: "status")

      static let _knownKeys: Set<Swift.String> = [
        "documentId",
        "status",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .documentId) {
        self.documentId = value
      }
      self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.documentId, forKey: .documentId)
      try container.encodeIfPresent(self.status, forKey: .status)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineMetadata.IndividualDocumentStatus"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The pipeline metadata.
  public enum OneOf_PipelineMetadata: Codable, Equatable, Sendable {
    /// The pipeline metadata for GcsIngest pipeline.
    indirect case gcsIngestPipelineMetadata(RunPipelineMetadata.GcsIngestPipelineMetadata?)
    /// The pipeline metadata for Export-to-CDW pipeline.
    indirect case exportToCdwPipelineMetadata(RunPipelineMetadata.ExportToCdwPipelineMetadata?)
    /// The pipeline metadata for Process-with-DocAi pipeline.
    indirect case processWithDocAiPipelineMetadata(
      RunPipelineMetadata.ProcessWithDocAiPipelineMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
