// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for DocumentService.RunPipeline.
public struct RunPipelineRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name which owns the resources of the pipeline.
  /// Format: projects/{project_number}/locations/{location}.
  public var name: Swift.String = Swift.String()

  /// The meta information collected about the end user, used to enforce access
  /// control for the service.
  public var requestMetadata: RequestMetadata? = nil

  /// The predefined pipelines.
  public var pipeline: OneOf_Pipeline? = nil

  /// Initialize a new instance of `RunPipelineRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RunPipelineRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case gcsIngestPipeline = "gcsIngestPipeline"
    case gcsIngestWithDocAiProcessorsPipeline = "gcsIngestWithDocAiProcessorsPipeline"
    case exportCdwPipeline = "exportCdwPipeline"
    case processWithDocAiPipeline = "processWithDocAiPipeline"
    case requestMetadata = "requestMetadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.requestMetadata = try container.decodeIfPresent(
      RequestMetadata.self, forKey: .requestMetadata)

    var pipeline: OneOf_Pipeline? = nil
    let pipelineCheckAndSet = {
      if pipeline != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pipeline'"))
      }
      pipeline = $0
    }
    if let gcsIngestPipeline = try container.decodeIfPresent(
      GcsIngestPipeline?.self, forKey: .gcsIngestPipeline)
    {
      try pipelineCheckAndSet(.gcsIngestPipeline(gcsIngestPipeline))
    }
    if let gcsIngestWithDocAiProcessorsPipeline = try container.decodeIfPresent(
      GcsIngestWithDocAiProcessorsPipeline?.self, forKey: .gcsIngestWithDocAiProcessorsPipeline)
    {
      try pipelineCheckAndSet(
        .gcsIngestWithDocAiProcessorsPipeline(gcsIngestWithDocAiProcessorsPipeline))
    }
    if let exportCdwPipeline = try container.decodeIfPresent(
      ExportToCdwPipeline?.self, forKey: .exportCdwPipeline)
    {
      try pipelineCheckAndSet(.exportCdwPipeline(exportCdwPipeline))
    }
    if let processWithDocAiPipeline = try container.decodeIfPresent(
      ProcessWithDocAiPipeline?.self, forKey: .processWithDocAiPipeline)
    {
      try pipelineCheckAndSet(.processWithDocAiPipeline(processWithDocAiPipeline))
    }
    self.pipeline = pipeline
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestMetadata, forKey: .requestMetadata)

    if let choice = self.pipeline {
      switch choice {
      case .gcsIngestPipeline(let value):
        try container.encode(value, forKey: .gcsIngestPipeline)
      case .gcsIngestWithDocAiProcessorsPipeline(let value):
        try container.encode(value, forKey: .gcsIngestWithDocAiProcessorsPipeline)
      case .exportCdwPipeline(let value):
        try container.encode(value, forKey: .exportCdwPipeline)
      case .processWithDocAiPipeline(let value):
        try container.encode(value, forKey: .processWithDocAiPipeline)
      }
    }
  }

  /// The predefined pipelines.
  public enum OneOf_Pipeline: Codable, Equatable, Sendable {
    /// Cloud Storage ingestion pipeline.
    indirect case gcsIngestPipeline(GcsIngestPipeline?)
    /// Use DocAI processors to process documents in Cloud Storage and ingest
    /// them to Document Warehouse.
    indirect case gcsIngestWithDocAiProcessorsPipeline(GcsIngestWithDocAiProcessorsPipeline?)
    /// Export docuemnts from Document Warehouse to CDW for training purpose.
    indirect case exportCdwPipeline(ExportToCdwPipeline?)
    /// Use a DocAI processor to process documents in Document Warehouse, and
    /// re-ingest the updated results into Document Warehouse.
    indirect case processWithDocAiPipeline(ProcessWithDocAiPipeline?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.RunPipelineRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
