// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for DocumentService.SearchDocuments.
public struct SearchDocumentsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of documents.
  /// Format: projects/{project_number}/locations/{location}.
  public var parent: Swift.String = Swift.String()

  /// The meta information collected about the end user, used to enforce access
  /// control and improve the search quality of the service.
  public var requestMetadata: RequestMetadata? = nil

  /// Query used to search against documents (keyword, filters, etc.).
  public var documentQuery: DocumentQuery? = nil

  /// An integer that specifies the current offset (that is, starting result
  /// location, amongst the documents deemed by the API as relevant) in search
  /// results. This field is only considered if
  /// [page_token][google.cloud.contentwarehouse.v1.SearchDocumentsRequest.page_token]
  /// is unset.
  ///
  /// The maximum allowed value is 5000. Otherwise an error is thrown.
  ///
  /// For example, 0 means to  return results starting from the first matching
  /// document, and 10 means to return from the 11th document. This can be used
  /// for pagination, (for example, pageSize = 10 and offset = 10 means to return
  /// from the second page).
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest.page_token]: <doc:SearchDocumentsRequest/pageToken>
  public var offset: Swift.Int32 = Swift.Int32()

  /// A limit on the number of documents returned in the search results.
  /// Increasing this value above the default value of 10 can increase search
  /// response time. The value can be between 1 and 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The token specifying the current offset within search results.
  /// See
  /// [SearchDocumentsResponse.next_page_token][google.cloud.contentwarehouse.v1.SearchDocumentsResponse.next_page_token]
  /// for an explanation of how to obtain the next set of query results.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsResponse.next_page_token]: <doc:SearchDocumentsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// The criteria determining how search results are sorted. For non-empty
  /// query, default is `"relevance desc"`. For empty query, default is
  /// `"upload_date desc"`.
  ///
  /// Supported options are:
  ///
  /// * `"relevance desc"`: By relevance descending, as determined by the API
  ///   algorithms.
  /// * `"upload_date desc"`: By upload date descending.
  /// * `"upload_date"`: By upload date ascending.
  /// * `"update_date desc"`: By last updated date descending.
  /// * `"update_date"`: By last updated date ascending.
  /// * `"retrieval_importance desc"`: By retrieval importance of properties
  ///   descending. This feature is still under development, please do not use
  ///   unless otherwise instructed to do so.
  public var orderBy: Swift.String = Swift.String()

  /// An expression specifying a histogram request against matching
  /// documents. Expression syntax is an aggregation function call with
  /// histogram facets and other options.
  ///
  /// The following aggregation functions are supported:
  ///
  /// * `count(string_histogram_facet)`: Count the number of matching entities
  /// for each distinct attribute value.
  ///
  /// Data types:
  ///
  /// * Histogram facet (aka filterable properties): Facet names with format
  /// &lt;schema id&gt;.&lt;facet&gt;. Facets will have the
  /// format of: `[a-zA-Z][a-zA-Z0-9_:/-.]`. If the facet is a child
  /// facet, then the parent hierarchy needs to be specified separated by
  /// dots in the prefix after the schema id. Thus, the format for a multi-
  /// level facet is: &lt;schema id&gt;.&lt;parent facet name&gt;.
  /// &lt;child facet name&gt;. Example:
  /// schema123.root_parent_facet.middle_facet.child_facet
  /// * DocumentSchemaId: (with no schema id prefix) to get
  /// histograms for each document type (returns the schema id path, e.g.
  /// projects/12345/locations/us-west/documentSchemas/abc123).
  ///
  /// Example expression:
  ///
  /// * Document type counts:
  ///   count('DocumentSchemaId')
  ///
  /// * For schema id, abc123, get the counts for MORTGAGE_TYPE:
  ///   count('abc123.MORTGAGE_TYPE')
  public var histogramQueries: [HistogramQuery] = []

  /// Controls if the search document request requires the return of a total size
  /// of matched documents. See
  /// [SearchDocumentsResponse.total_size][google.cloud.contentwarehouse.v1.SearchDocumentsResponse.total_size].
  ///
  /// Enabling this flag may adversely impact performance. Hint: If this is
  /// used with pagination, set this flag on the initial query but set this
  /// to false on subsequent page calls (keep the total count locally).
  ///
  /// Defaults to false.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsResponse.total_size]: <doc:SearchDocumentsResponse/totalSize>
  public var requireTotalSize: Swift.Bool = Swift.Bool()

  /// Controls if the search document request requires the return of a total size
  /// of matched documents. See
  /// [SearchDocumentsResponse.total_size][google.cloud.contentwarehouse.v1.SearchDocumentsResponse.total_size].
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsResponse.total_size]: <doc:SearchDocumentsResponse/totalSize>
  public var totalResultSize: SearchDocumentsRequest.TotalResultSize =
    SearchDocumentsRequest.TotalResultSize()

  /// Experimental, do not use.
  /// The limit on the number of documents returned for the question-answering
  /// feature. To enable the question-answering feature, set
  /// [DocumentQuery].[is_nl_query][] to true.
  public var qaSizeLimit: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `SearchDocumentsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchDocumentsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The total number of matching documents.
  public enum TotalResultSize: Codable, Equatable, Sendable {
    /// Total number calculation will be skipped.
    case unspecified
    /// Estimate total number. The total result size will be accurated up to
    /// 10,000. This option will add cost and latency to your request.
    case estimatedSize
    /// It may adversely impact performance. The limit is 1000,000.
    case actualSize
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .estimatedSize: return 1
      case .actualSize: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TOTAL_RESULT_SIZE_UNSPECIFIED"
      case .estimatedSize: return "ESTIMATED_SIZE"
      case .actualSize: return "ACTUAL_SIZE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TotalResultSize/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TOTAL_RESULT_SIZE_UNSPECIFIED": self = .unspecified
      case "ESTIMATED_SIZE": self = .estimatedSize
      case "ACTUAL_SIZE": self = .actualSize
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TotalResultSize/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .estimatedSize
      case 2: self = .actualSize
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .estimatedSize: return try container.encode(1)
      case .actualSize: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.SearchDocumentsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
