// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for DocumentService.SearchDocuments.
public struct SearchDocumentsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The document entities that match the specified
  /// [SearchDocumentsRequest][google.cloud.contentwarehouse.v1.SearchDocumentsRequest].
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest]: <doc:SearchDocumentsRequest>
  public var matchingDocuments: [SearchDocumentsResponse.MatchingDocument] = []

  /// The token that specifies the starting position of the next page of results.
  /// This field is empty if there are no more results.
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of matched documents which is available only if the client
  /// set
  /// [SearchDocumentsRequest.require_total_size][google.cloud.contentwarehouse.v1.SearchDocumentsRequest.require_total_size]
  /// to `true` or set
  /// [SearchDocumentsRequest.total_result_size][google.cloud.contentwarehouse.v1.SearchDocumentsRequest.total_result_size]
  /// to `ESTIMATED_SIZE` or `ACTUAL_SIZE`. Otherwise, the value will be `-1`.
  /// Typically a UI would handle this condition by displaying &quot;of
  /// many&quot;, for example: &quot;Displaying 10 of many&quot;.
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest.require_total_size]: <doc:SearchDocumentsRequest/requireTotalSize>
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest.total_result_size]: <doc:SearchDocumentsRequest/totalResultSize>
  public var totalSize: Swift.Int32 = Swift.Int32()

  /// Additional information for the API invocation, such as the request tracking
  /// id.
  public var metadata: ResponseMetadata? = nil

  /// The histogram results that match with the specified
  /// [SearchDocumentsRequest.histogram_queries][google.cloud.contentwarehouse.v1.SearchDocumentsRequest.histogram_queries].
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest.histogram_queries]: <doc:SearchDocumentsRequest/histogramQueries>
  public var histogramQueryResults: [HistogramQueryResult] = []

  /// Experimental.
  /// Question answer from the query against the document.
  public var questionAnswer: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchDocumentsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchDocumentsResponse().with { $0.matchingDocuments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let matchingDocuments = CodingKeys(stringValue: "matchingDocuments")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let histogramQueryResults = CodingKeys(stringValue: "histogramQueryResults")
    static let questionAnswer = CodingKeys(stringValue: "questionAnswer")

    static let _knownKeys: Set<Swift.String> = [
      "matchingDocuments",
      "nextPageToken",
      "totalSize",
      "metadata",
      "histogramQueryResults",
      "questionAnswer",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SearchDocumentsResponse.MatchingDocument].self, forKey: .matchingDocuments)
    {
      self.matchingDocuments = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    self.metadata = try container.decodeIfPresent(ResponseMetadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(
      [HistogramQueryResult].self, forKey: .histogramQueryResults)
    {
      self.histogramQueryResults = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .questionAnswer) {
      self.questionAnswer = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.matchingDocuments, forKey: .matchingDocuments)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.histogramQueryResults, forKey: .histogramQueryResults)
    try container.encode(self.questionAnswer, forKey: .questionAnswer)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Document entry with metadata inside
  /// [SearchDocumentsResponse][google.cloud.contentwarehouse.v1.SearchDocumentsResponse]
  ///
  /// [google.cloud.contentwarehouse.v1.SearchDocumentsResponse]: <doc:SearchDocumentsResponse>
  public struct MatchingDocument: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Document that matches the specified
    /// [SearchDocumentsRequest][google.cloud.contentwarehouse.v1.SearchDocumentsRequest].
    /// This document only contains indexed metadata information.
    ///
    /// [google.cloud.contentwarehouse.v1.SearchDocumentsRequest]: <doc:SearchDocumentsRequest>
    public var document: Document? = nil

    /// Contains snippets of text from the document full raw text that most
    /// closely match a search query's keywords, if available. All HTML tags in
    /// the original fields are stripped when returned in this field, and
    /// matching query keywords are enclosed in HTML bold tags.
    ///
    /// If the question-answering feature is enabled, this field will instead
    /// contain a snippet that answers the user's natural-language query. No HTML
    /// bold tags will be present, and highlights in the answer snippet can be
    /// found in
    /// [QAResult.highlights][google.cloud.contentwarehouse.v1.QAResult.highlights].
    ///
    /// [google.cloud.contentwarehouse.v1.QAResult.highlights]: <doc:QAResult/highlights>
    public var searchTextSnippet: Swift.String = Swift.String()

    /// Experimental.
    /// Additional result info if the question-answering feature is enabled.
    public var qaResult: QAResult? = nil

    /// Return the 1-based page indices where those pages have one or more
    /// matched tokens.
    public var matchedTokenPageIndices: [Swift.Int64] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `MatchingDocument`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MatchingDocument().with { $0.document = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let document = CodingKeys(stringValue: "document")
      static let searchTextSnippet = CodingKeys(stringValue: "searchTextSnippet")
      static let qaResult = CodingKeys(stringValue: "qaResult")
      static let matchedTokenPageIndices = CodingKeys(stringValue: "matchedTokenPageIndices")

      static let _knownKeys: Set<Swift.String> = [
        "document",
        "searchTextSnippet",
        "qaResult",
        "matchedTokenPageIndices",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.document = try container.decodeIfPresent(Document.self, forKey: .document)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchTextSnippet) {
        self.searchTextSnippet = value
      }
      self.qaResult = try container.decodeIfPresent(QAResult.self, forKey: .qaResult)
      if let value = try container.decodeIfPresent(
        [Swift.Int64].self, forKey: .matchedTokenPageIndices)
      {
        self.matchedTokenPageIndices = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.document, forKey: .document)
      try container.encode(self.searchTextSnippet, forKey: .searchTextSnippet)
      try container.encodeIfPresent(self.qaResult, forKey: .qaResult)
      try container.encode(self.matchedTokenPageIndices, forKey: .matchedTokenPageIndices)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contentwarehouse.v1.SearchDocumentsResponse.MatchingDocument"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.SearchDocumentsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [SearchDocumentsResponse.MatchingDocument] {
    return self.matchingDocuments
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
