// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class SynonymSetServiceRetry: SynonymSetServiceStub {
    let inner: any SynonymSetServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any SynonymSetServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createSynonymSet(
      request: CreateSynonymSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSynonymSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.SynonymSet
          in
          return try await self.inner.createSynonymSet(request: r, options: o)
        })
    }

    public func getSynonymSet(
      request: GetSynonymSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSynonymSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.SynonymSet
          in
          return try await self.inner.getSynonymSet(request: r, options: o)
        })
    }

    public func updateSynonymSet(
      request: UpdateSynonymSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSynonymSetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.SynonymSet
          in
          return try await self.inner.updateSynonymSet(request: r, options: o)
        })
    }

    public func deleteSynonymSet(
      request: DeleteSynonymSetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteSynonymSetRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSynonymSet(request: r, options: o)
        })
    }

    public func listSynonymSets(
      request: ListSynonymSetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSynonymSetsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse
          in
          return try await self.inner.listSynonymSets(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
