// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// A Service that manage/custom customer specified SynonymSets.
///
/// @Snippet(path: "SynonymSetServiceQuickstart")
public final class SynonymSetServiceClient: Clients.SynonymSetServiceProtocol, Sendable {
  let inner: any Clients.SynonymSetServiceStub

  /// Creates a new `SynonymSetServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.SynonymSetServiceStub = try Clients.SynonymSetServiceTransport(options)
    inner = Clients.SynonymSetServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SynonymSetServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a SynonymSet for a single context.
  /// Throws an ALREADY_EXISTS exception if a synonymset already exists
  /// for the context.
  ///
  /// @Snippet(path: "SynonymSetService_CreateSynonymSet")
  public func createSynonymSet(
    request: CreateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    try await self.inner.createSynonymSet(request: request, options: options)
  }

  /// Gets a SynonymSet for a particular context.
  /// Throws a NOT_FOUND exception if the Synonymset
  /// does not exist
  ///
  /// @Snippet(path: "SynonymSetService_GetSynonymSet")
  public func getSynonymSet(
    request: GetSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    try await self.inner.getSynonymSet(request: request, options: options)
  }

  /// Remove the existing SynonymSet for the context and replaces it
  /// with a new one.
  /// Throws a NOT_FOUND exception if the SynonymSet is not found.
  ///
  /// @Snippet(path: "SynonymSetService_UpdateSynonymSet")
  public func updateSynonymSet(
    request: UpdateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    try await self.inner.updateSynonymSet(request: request, options: options)
  }

  /// Deletes a SynonymSet for a given context.
  /// Throws a NOT_FOUND exception if the SynonymSet is not found.
  ///
  /// @Snippet(path: "SynonymSetService_DeleteSynonymSet")
  public func deleteSynonymSet(
    request: DeleteSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSynonymSet(request: request, options: options)
  }

  /// Returns all SynonymSets (for all contexts) for the specified location.
  ///
  /// @Snippet(path: "SynonymSetService_ListSynonymSets")
  public func listSynonymSets(
    request: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse {
    try await self.inner.listSynonymSets(request: request, options: options)
  }

  /// Returns all SynonymSets (for all contexts) for the specified location.
  ///
  /// @Snippet(path: "SynonymSetService_ListSynonymSets")
  public func listSynonymSets(
    byItem: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SynonymSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSynonymSets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "SynonymSetService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SynonymSetServiceClient`.
  ///
  /// To mock `SynonymSetServiceClient` change your functions to receive
  /// `some SynonymSetServiceProtocol` or `any SynonymSetServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SynonymSetServiceProtocol {
    /// See `SynonymSetServiceClient.createSynonymSet`.
    func createSynonymSet(request: CreateSynonymSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.createSynonymSet`.
    func createSynonymSet(
      parent: Swift.String,
      synonymSet: SynonymSet?,
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.getSynonymSet`.
    func getSynonymSet(request: GetSynonymSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.getSynonymSet`.
    func getSynonymSet(
      name: Swift.String,
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.updateSynonymSet`.
    func updateSynonymSet(request: UpdateSynonymSetRequest) async throws
      -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.updateSynonymSet`.
    func updateSynonymSet(
      name: Swift.String,
      synonymSet: SynonymSet?,
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.deleteSynonymSet`.
    func deleteSynonymSet(request: DeleteSynonymSetRequest) async throws

    /// See `SynonymSetServiceClient.deleteSynonymSet`.
    func deleteSynonymSet(
      name: Swift.String,
    ) async throws

    /// See `SynonymSetServiceClient.listSynonymSets`.
    func listSynonymSets(request: ListSynonymSetsRequest) async throws
      -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse

    /// See `SynonymSetServiceClient.listSynonymSets`.
    func listSynonymSets(
      byItem: ListSynonymSetsRequest
    ) throws -> any AsyncSequence<SynonymSet, Swift.Error>

    /// See `SynonymSetServiceClient.listSynonymSets`.
    func listSynonymSets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SynonymSet, Swift.Error>

    /// See `SynonymSetServiceClient.createSynonymSet`.
    func createSynonymSet(
      request: CreateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.getSynonymSet`.
    func getSynonymSet(
      request: GetSynonymSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.updateSynonymSet`.
    func updateSynonymSet(
      request: UpdateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet

    /// See `SynonymSetServiceClient.deleteSynonymSet`.
    func deleteSynonymSet(
      request: DeleteSynonymSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `SynonymSetServiceClient.listSynonymSets`.
    func listSynonymSets(
      request: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse

    /// See `SynonymSetServiceClient.listSynonymSets`.
    func listSynonymSets(
      byItem: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SynonymSet, Swift.Error>
  }
}

// Default implementations
extension Clients.SynonymSetServiceProtocol {
  public func createSynonymSet(request: CreateSynonymSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.SynonymSet
  {
    try await self.createSynonymSet(request: request, options: .init())
  }

  public func createSynonymSet(
    request: CreateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSynonymSet(
    parent: Swift.String,
    synonymSet: SynonymSet?,
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    let request = CreateSynonymSetRequest().with {
      $0.parent = parent
      $0.synonymSet = synonymSet
    }
    return try await self.createSynonymSet(request: request)
  }

  public func getSynonymSet(request: GetSynonymSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.SynonymSet
  {
    try await self.getSynonymSet(request: request, options: .init())
  }

  public func getSynonymSet(
    request: GetSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSynonymSet(
    name: Swift.String,
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    let request = GetSynonymSetRequest().with {
      $0.name = name
    }
    return try await self.getSynonymSet(request: request)
  }

  public func updateSynonymSet(request: UpdateSynonymSetRequest) async throws
    -> GoogleCloudContentWarehouseV1.SynonymSet
  {
    try await self.updateSynonymSet(request: request, options: .init())
  }

  public func updateSynonymSet(
    request: UpdateSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSynonymSet(
    name: Swift.String,
    synonymSet: SynonymSet?,
  ) async throws -> GoogleCloudContentWarehouseV1.SynonymSet {
    let request = UpdateSynonymSetRequest().with {
      $0.name = name
      $0.synonymSet = synonymSet
    }
    return try await self.updateSynonymSet(request: request)
  }

  public func deleteSynonymSet(request: DeleteSynonymSetRequest) async throws {
    try await self.deleteSynonymSet(request: request, options: .init())
  }

  public func deleteSynonymSet(
    request: DeleteSynonymSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSynonymSet(
    name: Swift.String,
  ) async throws {
    let request = DeleteSynonymSetRequest().with {
      $0.name = name
    }
    try await self.deleteSynonymSet(request: request)
  }

  public func listSynonymSets(request: ListSynonymSetsRequest) async throws
    -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse
  {
    try await self.listSynonymSets(request: request, options: .init())
  }

  public func listSynonymSets(
    request: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSynonymSets(
    byItem: ListSynonymSetsRequest
  ) throws -> any AsyncSequence<SynonymSet, Swift.Error> {
    try self.listSynonymSets(byItem: byItem, options: .init())
  }

  public func listSynonymSets(
    byItem: ListSynonymSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SynonymSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudContentWarehouseV1.ListSynonymSetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSynonymSets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SynonymSet, Swift.Error> {
    let request = ListSynonymSetsRequest().with {
      $0.parent = parent
    }
    return try self.listSynonymSets(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
