// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for DocumentService.UpdateDocument.
public struct UpdateDocumentRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the document to update.
  /// Format:
  /// projects/{project_number}/locations/{location}/documents/{document_id}
  /// or
  /// projects/{project_number}/locations/{location}/documents/referenceId/{reference_id}.
  public var name: Swift.String = Swift.String()

  /// Required. The document to update.
  public var document: Document? = nil

  /// The meta information collected about the end user, used to enforce access
  /// control for the service.
  public var requestMetadata: RequestMetadata? = nil

  /// Request Option for processing Cloud AI Document in Document Warehouse.
  /// This field offers limited support for mapping entities from Cloud AI
  /// Document to Warehouse Document. Please consult with product team before
  /// using this field and other available options.
  public var cloudAiDocumentOption: CloudAIDocumentOption? = nil

  /// Options for the update operation.
  public var updateOptions: UpdateOptions? = nil

  /// Initialize a new instance of `UpdateDocumentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateDocumentRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.UpdateDocumentRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
