// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Update type of the requests.
public enum UpdateType: Codable, Equatable, Sendable {
  /// Defaults to full replace behavior, ie. FULL_REPLACE.
  case unspecified
  /// Fully replace all the fields (including previously linked raw document).
  /// Any field masks will be ignored.
  case replace
  /// Merge the fields into the existing entities.
  case merge
  /// Inserts the properties by names.
  case insertPropertiesByNames
  /// Replace the properties by names.
  case replacePropertiesByNames
  /// Delete the properties by names.
  case deletePropertiesByNames
  /// For each of the property, replaces the property if the it exists, otherwise
  /// inserts a new property. And for the rest of the fields, merge them based on
  /// update mask and merge fields options.
  case mergeAndReplaceOrInsertPropertiesByNames
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .replace: return 1
    case .merge: return 2
    case .insertPropertiesByNames: return 3
    case .replacePropertiesByNames: return 4
    case .deletePropertiesByNames: return 5
    case .mergeAndReplaceOrInsertPropertiesByNames: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "UPDATE_TYPE_UNSPECIFIED"
    case .replace: return "UPDATE_TYPE_REPLACE"
    case .merge: return "UPDATE_TYPE_MERGE"
    case .insertPropertiesByNames: return "UPDATE_TYPE_INSERT_PROPERTIES_BY_NAMES"
    case .replacePropertiesByNames: return "UPDATE_TYPE_REPLACE_PROPERTIES_BY_NAMES"
    case .deletePropertiesByNames: return "UPDATE_TYPE_DELETE_PROPERTIES_BY_NAMES"
    case .mergeAndReplaceOrInsertPropertiesByNames:
      return "UPDATE_TYPE_MERGE_AND_REPLACE_OR_INSERT_PROPERTIES_BY_NAMES"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UpdateType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "UPDATE_TYPE_UNSPECIFIED": self = .unspecified
    case "UPDATE_TYPE_REPLACE": self = .replace
    case "UPDATE_TYPE_MERGE": self = .merge
    case "UPDATE_TYPE_INSERT_PROPERTIES_BY_NAMES": self = .insertPropertiesByNames
    case "UPDATE_TYPE_REPLACE_PROPERTIES_BY_NAMES": self = .replacePropertiesByNames
    case "UPDATE_TYPE_DELETE_PROPERTIES_BY_NAMES": self = .deletePropertiesByNames
    case "UPDATE_TYPE_MERGE_AND_REPLACE_OR_INSERT_PROPERTIES_BY_NAMES":
      self = .mergeAndReplaceOrInsertPropertiesByNames
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UpdateType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .replace
    case 2: self = .merge
    case 3: self = .insertPropertiesByNames
    case 4: self = .replacePropertiesByNames
    case 5: self = .deletePropertiesByNames
    case 6: self = .mergeAndReplaceOrInsertPropertiesByNames
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .replace: return try container.encode(1)
    case .merge: return try container.encode(2)
    case .insertPropertiesByNames: return try container.encode(3)
    case .replacePropertiesByNames: return try container.encode(4)
    case .deletePropertiesByNames: return try container.encode(5)
    case .mergeAndReplaceOrInsertPropertiesByNames: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
