// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for DocumentService.UpdateDocument.
public struct UpdateDocumentResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Updated document after executing update request.
  public var document: Document? = nil

  /// Output from Rule Engine recording the rule evaluator and action executor's
  /// output.
  ///
  /// Refer format in: google/cloud/contentwarehouse/v1/rule_engine.proto
  public var ruleEngineOutput: RuleEngineOutput? = nil

  /// Additional information for the API invocation, such as the request tracking
  /// id.
  public var metadata: ResponseMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateDocumentResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateDocumentResponse().with { $0.document = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let document = CodingKeys(stringValue: "document")
    static let ruleEngineOutput = CodingKeys(stringValue: "ruleEngineOutput")
    static let metadata = CodingKeys(stringValue: "metadata")

    static let _knownKeys: Set<Swift.String> = [
      "document",
      "ruleEngineOutput",
      "metadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.document = try container.decodeIfPresent(Document.self, forKey: .document)
    self.ruleEngineOutput = try container.decodeIfPresent(
      RuleEngineOutput.self, forKey: .ruleEngineOutput)
    self.metadata = try container.decodeIfPresent(ResponseMetadata.self, forKey: .metadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.document, forKey: .document)
    try container.encodeIfPresent(self.ruleEngineOutput, forKey: .ruleEngineOutput)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.UpdateDocumentResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
