// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// `Value` represents a dynamically typed value which can be either be
/// a float, a integer, a string, or a datetime value. A producer of value is
/// expected to set one of these variants. Absence of any variant indicates an
/// error.
public struct Value: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The kind of value.
  public var kind: OneOf_Kind? = nil

  /// Initialize a new instance of `Value`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Value().with { $0.floatValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case floatValue = "floatValue"
    case intValue = "intValue"
    case stringValue = "stringValue"
    case enumValue = "enumValue"
    case datetimeValue = "datetimeValue"
    case timestampValue = "timestampValue"
    case booleanValue = "booleanValue"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var kind: OneOf_Kind? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let floatValue = try container.decodeIfPresent(Swift.Float.self, forKey: .floatValue) {
      try kindCheckAndSet(.floatValue(floatValue))
    }
    if let intValue = try container.decodeIfPresent(Swift.Int32.self, forKey: .intValue) {
      try kindCheckAndSet(.intValue(intValue))
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try kindCheckAndSet(.stringValue(stringValue))
    }
    if let enumValue = try container.decodeIfPresent(EnumValue?.self, forKey: .enumValue) {
      try kindCheckAndSet(.enumValue(enumValue))
    }
    if let datetimeValue = try container.decodeIfPresent(
      GoogleType.DateTime?.self, forKey: .datetimeValue)
    {
      try kindCheckAndSet(.datetimeValue(datetimeValue))
    }
    if let timestampValue = try container.decodeIfPresent(
      TimestampValue?.self, forKey: .timestampValue)
    {
      try kindCheckAndSet(.timestampValue(timestampValue))
    }
    if let booleanValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .booleanValue) {
      try kindCheckAndSet(.booleanValue(booleanValue))
    }
    self.kind = kind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.kind {
      switch choice {
      case .floatValue(let value):
        try container.encode(value, forKey: .floatValue)
      case .intValue(let value):
        try container.encode(value, forKey: .intValue)
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .enumValue(let value):
        try container.encode(value, forKey: .enumValue)
      case .datetimeValue(let value):
        try container.encode(value, forKey: .datetimeValue)
      case .timestampValue(let value):
        try container.encode(value, forKey: .timestampValue)
      case .booleanValue(let value):
        try container.encode(value, forKey: .booleanValue)
      }
    }
  }

  /// The kind of value.
  public enum OneOf_Kind: Codable, Equatable, Sendable {
    /// Represents a float value.
    case floatValue(Swift.Float)
    /// Represents a integer value.
    case intValue(Swift.Int32)
    /// Represents a string value.
    case stringValue(Swift.String)
    /// Represents an enum value.
    indirect case enumValue(EnumValue?)
    /// Represents a datetime value.
    indirect case datetimeValue(GoogleType.DateTime?)
    /// Represents a timestamp value.
    indirect case timestampValue(TimestampValue?)
    /// Represents a boolean value.
    case booleanValue(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contentwarehouse.v1.Value"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
